change ZKP section
w3c/vc-data-model pull request #1030
Opened 2023-02-08 00:33 UTC by brentzundel

This PR:

- Adds a version of the note initially drafter by Orie in #1026 
- modernizes and generalizes the language in the section in an attempt to make it more applicable to various zero knowledge proof mechanisms.
- adds a note that the examples will either be re-worked or removed.

I believe this PR prepares this section for for one of these possibilities:
1. The WG normatively specifies a method for securing VCs that supports ZKPs, in which case the examples and normative language in this section could be easily updated.
2. The WG does not normatively specify a method for securing VCs that supports ZKPs, in which case the examples and normative language in this section would be removed, and the remaining language could be moved to the implementation guide.

Signed-off-by: Brent Zundel <brent.zundel@gmail.com>

2023-02-08 19:56 UTC, TallTed commented on index.html
> +made possible by zero-knowledge proof mechanisms:
```suggestion
The following are some capabilities that are compatible with
<a>verifiable credentials</a>, that are made possible by zero-knowledge
proof mechanisms:
```

2023-02-08 19:58 UTC, TallTed commented on index.html
> +Blinding of the signature value that is shared with a <a>verifier</a>. This
```suggestion
<b>Blinding of the signature value that is shared with a <a>verifier</a>.</b> This
```

2023-02-08 19:59 UTC, TallTed commented on index.html
> +Privacy preserving identification of the <a>holder</a>/<a>subject</a>. This
```suggestion
<b>Privacy preserving identification of the <a>holder</a> and/or <a>subject</a>.</b> This
```

2023-02-08 20:01 UTC, TallTed commented on index.html
> +We note that in most instances, for <a>holder</a> to make use of zero knowledge
```suggestion
We note that in most instances, for a <a>holder</a> to make use of zero knowledge
```

2023-02-09 10:41 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-02-08-vcwg#section3-2) on 2023-02-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.2. change ZKP section (pr vc-data-model#1030)

_See github pull request [vc-data-model#1030](https://github.com/w3c/vc-data-model/pull/1030)._




**Brent Zundel:** should be straightforward to adjust further or get rid of the section.  

**Manu Sporny:** orie suggests process in order. Doing that.  
… processing #1026, #1028 then need review on #1030.  

</details>

2023-02-10 21:49 UTC, quartzjer approved these changes

2023-02-10 21:49 UTC, quartzjer commented on index.html
> +knowledge proof mechanisms when we transition v2 of the data model to CR.
```suggestion
knowledge proof mechanisms when we transition to v2 of the data model to CR.
```

2023-02-10 21:49 UTC, quartzjer commented on index.html
> +to secure a <a>verifiable credential</a> using a normatively defined method that
```suggestion
to secure a <a>verifiable credential</a> using normatively defined methods that
```

2023-02-12 21:32 UTC, dlongley approved these changes
I remain a bit concerned about over promising what ZKP can realistically do in various use cases, but this text hasn't changed that much from what was originally approved to be in the VCDM 1.1 spec and there will be another revision at some point in the future before 2.0 is finished, so +1. Thanks for cleaning this up!

2023-02-12 21:32 UTC, dlongley commented on index.html
> +proof mechanisms:
```suggestion
<a>verifiable credentials</a>, made possible by zero-knowledge
proof mechanisms:
```

2023-02-12 21:32 UTC, dlongley commented on index.html
> +<a>verifier</a> with precisely the information they need and nothing more.
```suggestion
<a>verifier</a> with precisely the information they request and nothing more.
```

2023-02-12 21:44 UTC, Sakurann reviewed
Selective disclosure, derived claim and unlinkability are three distinct features. By ZKP do we mean a way to secure VCs that fulfill all three or at least one? This needs to be clear. In the former, I think it is highly unlikely we will have a mature way before VC-data-model v2 CR, if the latter, SD-JWT will fall under this umbrella, but then the section name should be renamed from "ZKP".

2023-02-13 16:34 UTC, brentzundel commented
> Selective disclosure, derived claim and unlinkability are three distinct features. By ZKP do we mean a way to secure VCs that fulfill all three or at least one? This needs to be clear. In the former, I think it is highly unlikely we will have a mature way before VC-data-model v2 CR, if the latter, SD-JWT will fall under this umbrella, but then the section name should be renamed from "ZKP".

I agree that if SD-JWT becomes a normative part of the spec, then this section should be expanded to include it.

2023-02-13 22:34 UTC, TallTed requested changes

2023-02-13 22:34 UTC, TallTed commented on index.html
> +knowledge proof mechanisms when we transition to v2 of the data model to CR.
If this doesn't make sense to you, try reading both versions of the line aloud.
```suggestion
knowledge proof mechanisms when we transition v2 of the data model to CR.
```

2023-02-13 22:34 UTC, TallTed commented on index.html
>  secure the <a>verifiable credential</a> in a manner that supports these
```suggestion
mechanisms with <a>verifiable credentials</a> requires the <a>issuer</a> to
have secured the <a>verifiable credential</a> in a manner that supports these
```

2023-02-15 15:48 UTC, Sakurann requested changes
it should be clear that the properties being discussed are mainly Selective Disclosure and unlinkability (via derivatives and identifier clinding), and one mechanism does not have to achieve all three at the same time.

2023-02-15 15:48 UTC, Sakurann commented on index.html
>          <h3>Zero-Knowledge Proofs</h3>
```suggestion
        <h3>Selective Disclosure and Unlinkability</h3>
```

2023-02-20 21:01 UTC, msporny commented on index.html
> +        <p class="note">
```suggestion
        <p class="issue" title="ZKP examples need to be updated">
```

2023-02-20 21:02 UTC, msporny approved these changes
Approving as long as minor nits are fixed.

2023-03-01 00:10 UTC, brentzundel commented on index.html
>          </p>
```suggestion
capabilities.
        </p>
        <p>
It should also be noted that zero-knowledge proof mechanisms are not the only
means of providing the above-mentioned capabilities. 
        </p>
```

2023-03-01 00:12 UTC, brentzundel commented
@Sakurann and @TallTed I have made changes to the PR to reflect your comments. Please re-review.

2023-03-01 00:51 UTC, TallTed approved these changes
Much better than it was.

2023-03-04 22:49 UTC, msporny commented
Merging this is currently blocked by @Sakurann. I've requested an explicit re-review. @Sakurann, please re-review the changes that @brentzundel has made to this PR so we can either merge it, or make further changes to address your concerns.

2023-03-08 07:18 UTC, tplooker approved these changes

2023-03-13 18:39 UTC, Sakurann approved these changes
Despite the change in the title, the section is still all about "zero-knowledge proof", which is a specific term and would not include things like SD-JWT. But given there are caveats to rewrite/remove this section written in the text, will keep the reservations until when that PR comes in later.

2023-03-13 18:39 UTC, Sakurann commented on index.html
> +Not all capabilities are supported in all zero-knowledge proof mechanisms.
```suggestion
Not all capabilities are supported in each zero-knowledge proof mechanisms.
```

2023-03-13 21:19 UTC, TallTed commented on index.html
> +Not all capabilities are supported in all zero-knowledge proof mechanisms.
```suggestion
A given zero-knowledge proof mechanism might not support all capabilities described here.
```

2023-03-15 10:25 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-03-14-vcwg-special#section2-2) on 2023-03-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.2. change ZKP section (pr vc-data-model#1030)

_See github pull request [vc-data-model#1030](https://github.com/w3c/vc-data-model/pull/1030)._




**Manu Sporny:** I think we're ready to merge this.  
… There are some changes that Kristina and Ted have suggested, but I think those are good to go unless someone here objects.  

> *Dave Longley:* +1 to merge with whatever editorial fixes.

**Brent Zundel:** ok, I'll apply language and merge.  

</details>

2023-03-21 17:56 UTC, TallTed commented on index.html
> +made possible by zero-knowledge proof mechanisms:
```suggestion
Some capabilities that are compatible with <a>verifiable credentials</a> which
are made possible by zero-knowledge proof mechanisms:
```

2023-03-21 18:02 UTC, TallTed commented on index.html
> +share. This capability can also be used to combine multiple
```suggestion
be shared. This capability can also be used to combine multiple
```

2023-03-22 17:10 UTC, David-Chadwick commented
Have you considered the impact of these edits on section 5.4 (data schemas) as this has an example that concerns ZKPs. Are edits also needed to this section?

2023-03-23 16:44 UTC, merged

2023-04-13 07:38 UTC, Sebastian-Elfors-IDnow commented
Thanks for the re-write of the ZKP section. It's a great improvement.

For completeness, the term "unlinkability" could be introduced. It is related to the bullet about "blinded signatures", which could be extended as follows: 

"Blinded signatures also allows for unlinkable proofs, which removes a common source of correlatable properties about a holder during multiple presentations to one or more verifiers."