Remove eg and ie
w3c/vc-data-model pull request #1045
Opened 2023-02-15 15:52 UTC by decentralgabe

Fixes https://github.com/w3c/vc-data-model/issues/1025

2023-02-15 17:20 UTC, iherman commented
I am not native English, so it is difficult for me to judge this. But what is wrong with "i.e.," or "e.g.,"? Or is it a difference between British and American English (I myself learned British English, originally.)

2023-02-15 17:27 UTC, decentralgabe commented
> I am not native English, so it is difficult for me to judge this. But what is wrong with "i.e.," or "e.g.,"? Or is it a difference between British and American English (I myself learned British English, originally.)

Seems like an internationalization issue https://github.com/w3c/vc-data-model/pull/1023#discussion_r1093301954

2023-02-15 18:06 UTC, TallTed commented
Yes, this was originally raised (elsewhere) by an i18n review.

2023-02-15 18:07 UTC, TallTed requested changes
colons are generally overkill here, breaking the flow more than needed

2023-02-15 18:07 UTC, TallTed commented on index.html
> +            IDs), such as: government ID, shipping address, credit card
```suggestion
            IDs), such as government ID, shipping address, credit card
```

2023-02-15 18:07 UTC, TallTed commented on index.html
> +            (personally identifiable info), such as: name, birthday, zip
```suggestion
            (personally identifiable info), such as name, birthday, zip
```

2023-02-15 18:07 UTC, TallTed commented on index.html
> +            (pseudonyms), such as: age over 21'.">
```suggestion
            (pseudonyms), such as age over 21'.">
```

2023-02-16 08:38 UTC, iherman approved these changes

2023-02-17 00:44 UTC, dlongley approved these changes

2023-02-17 08:13 UTC, peacekeeper approved these changes

2023-02-17 09:44 UTC, msporny approved these changes

2023-02-17 10:36 UTC, peacekeeper commented
I asked a professional English language editor in my family...

> We're working on a technical specification document, and someone said we should avoid "e.g." and "i.e.", and instead write "such as" and "that is". As a professional editor, do you agree with this?

Her reply:

> No, you can write both ways, especially on technical documents you can use e.g., and i.e., with commas

Me again:

> They say "e.g.," is difficult for some non-native English readers, and therefore for an international audience it should be avoided.

Her again:

> Disagree, but let them do what they want :)

2023-02-17 14:58 UTC, TallTed commented
If we decide to keep them (which will require standing up to at least some i18n reviewers), I will note she also advised, `with commas`. :-)

2023-02-20 21:57 UTC, msporny commented
@TallTed wrote:
> which will require standing up to at least some i18n reviewers

Hey @r12a, @bert-github, @fantasai, @frivoal, @himorin, @xfq,

The perennial question of whether or not W3C specifications should use latin abbreviations like "e.g.," or if it is preferable to write "for example" instead (from an internationalization standpoint). The last time I checked with some of you, the advice was to always prefer language that required less proficiency in English over language that used latin abbreviations (greater proficiency in English). 

Is that still the current guidance for W3C specifications?

2023-02-21 09:40 UTC, iherman commented
> The last time I checked with some of you, the advice was to always prefer language that required less proficiency in English over language that used latin abbreviations (greater proficiency in English).

I am really surprised by all this. Although it was a very long time ago ☹️ I still remember that when I started to learn English (to be specific, essentially British English because we were in Europe) the "e.g." and "i.e." abbreviations were introduced very early. It was part of the basics.

2023-02-21 16:11 UTC, decentralgabe commented
Any objections to merging this as is?

2023-02-22 01:01 UTC, Sakurann approved these changes

2023-02-22 15:05 UTC, mkhraisha approved these changes

2023-02-23 16:53 UTC, aphillips commented
@msporny et al regarding: https://github.com/w3c/vc-data-model/pull/1045#issuecomment-1437594686

The I18N WG is somewhat surprised by this thread. We are not aware of our having--now or in the past--a policy against (mostly Latin derived) abbreviated terms common to English such as `i.e.`, `e.g.`, `cf.`, `etc.` and so forth. If one or another of us made this comment in the past, this is to say: we didn't mean it/sorry.

I do note that some writers or organizations have style guides that prefer spelled out English terms (for clarity in English), but I18N does not take a position on this. I double-checked the [W3C Manual of Style](https://www.w3.org/Guide/manual-of-style/) and it is silent on this topic, so I suppose it is not a W3C policy either.

2023-02-23 17:56 UTC, decentralgabe commented
Thanks @aphillips I'm open to closing this. I will note there are other places in the spec (outside these changes) that have already removed latin usages. For consistency we'll want to revert them too - if we go down the path of keeping latin.

2023-02-23 18:44 UTC, TallTed commented
> For consistency we'll want to revert them

It's great that we now have a clear statement from the I18n WG, and we can keep existin `e.g.` or `i.e.` *if* the meaning of the use is clear, which is not always the case.

That said, I don't see a necessity to use `e.g.` or `i.e.` everywhere they *could* be used, nor to revert every instance we've changed to an appropriate English phrase to the relevant Latin abbreviation.  This kind of consistency is not the same as consistent use of relevant technical vocabulary.

2023-03-01 23:58 UTC, brentzundel commented
sounds like this can be closed, yes?

2023-03-01 23:59 UTC, decentralgabe commented
Closing as no longer needed.

2023-03-01 23:59 UTC, closed without merging