update json schema to accurately reflect context defn
w3c/vc-data-model pull request #1064
Opened 2023-03-13 21:16 UTC by decentralgabe

fixes #1059

2023-03-15 13:46 UTC, OR13 commented on schema/verifiable-credential/example-1.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:47 UTC, OR13 commented on schema/verifiable-credential/example-11.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:47 UTC, OR13 commented on schema/verifiable-credential/example-12.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:47 UTC, OR13 commented on schema/verifiable-credential/example-13.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:48 UTC, OR13 commented on schema/verifiable-credential/example-20.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:48 UTC, OR13 commented on schema/verifiable-credential/example-21.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:48 UTC, OR13 commented on schema/verifiable-credential/example-4.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:48 UTC, OR13 commented on schema/verifiable-presentation/example-2.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:48 UTC, OR13 commented on schema/verifiable-presentation/example-2.json
> +      "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:48 UTC, OR13 commented on schema/verifiable-presentation/example-25.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:48 UTC, OR13 commented on schema/verifiable-presentation/example-25.json
> +        "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:49 UTC, OR13 commented on schema/verifiable-presentation/example-45.json
> +    "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:49 UTC, OR13 commented on schema/verifiable-presentation/example-45.json
> +        "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 13:49 UTC, OR13 commented on schema/verifiable-presentation/example-45.json
> +        "https://www.w3.org/ns/credentials/examples/v2"
```suggestion
```

2023-03-15 16:03 UTC, decentralgabe commented
@OR13 I don't believe your comment is suitable for this PR, as I have followed the convention already in use by the current draft. See https://github.com/w3c/vc-data-model/blob/main/index.html#L980 for an example.

If you wish to modify the examples context that should come separately.

2023-03-15 16:47 UTC, OR13 commented
@msporny @decentralgabe this PR adds examples that are malformed, because:

- https://www.w3.org/ns/credentials/examples/v2 is 404.

There is no consensus to make "https://www.w3.org/ns/credentials/examples/v2" not 404, and as you can probably tell, I am strongly opposed to repeating the mistakes made in v1.1 again in v2, because it has been a source of implementation burden, it injects bias, and it leads to needlessly complicated examples and tests.

Given the current PR would introduce broken examples, please accept my change suggestion and file an issue to discuss "making https://www.w3.org/ns/credentials/examples/v2 not 404".

I remain opposed to merging this PR without my suggestions being accepted.

2023-03-15 17:19 UTC, OR13 commented
Related PR: https://github.com/w3c/vc-data-model/pull/1066

2023-03-16 09:50 UTC, iherman commented
Didn't we introduce the `@vocab` feature into the `@context` so that, for example, `https://www.w3.org/ns/credentials/examples/v2 ` would not be necessary any more? Maintaining properly yet another vocabulary seems an unnecessary burden to me in the current situation...

2023-03-16 14:10 UTC, msporny commented
> Didn't we introduce the `@vocab` feature into the `@context` so that, for example, `https://www.w3.org/ns/credentials/examples/v2 ` would not be necessary any more? Maintaining properly yet another vocabulary seems an unnecessary burden to me in the current situation...

Sure, but you're talking about the base examples that people see and work with. Specifically, all the examples, without an `examples/v2` context, are already confusing people... "I'm getting a bunch of undefined terms... why? Is that supposed to happen? What am I doing wrong?" -- which is the sort of experience we want people to have and then improve... but when our base examples in the core spec do that (same for Data Integrity), implementers get (rightly) concerned.

2023-03-16 14:50 UTC, msporny commented
@msporny wrote:
> If this is not acceptable

At this point, given the confusion that only having the base context has created (in the few weeks that we've tried to work with examples that only contain it), I expect DB would be a -1 for having the core examples in the specification not reflect what things like plugfests are using.

> then a proper vocabulary specification should be prepared for all the example terms, using the yaml2vocab tool, and then a redirection in the /ns space. (Is it worth it?)

An alternative would be to use existing JSON-LD Contexts that are being used for pilot or production settings. These include the Open Badges, GS1, Traceability, and Citizenship contexts.

2023-03-16 18:57 UTC, decentralgabe commented
@OR13 I'd like to note that the changes I made are copies of the examples in the spec itself, so they should not be controversial whatsoever.

If the spec changes, then this examples are downstream and should be updated. This is not the place to discuss them. As it stands the examples I had are in conflict with the spec.

2023-03-16 22:35 UTC, OR13 commented
Your examples and the core spec are both malformed. 

I am requesting they be well formed. 

I opened a PR to fix the core spec.

There is more than one way to "fix" this, but I think we should try the simpler solutions, before we try the more complicated ones.

2023-03-21 19:55 UTC, gkellogg commented
> B.t.w., the [JSON-LD 1.1 specification](https://www.w3.org/TR/json-ld11/) did the nice tricks of creating a tab for each JSON-LD example, linking to the code snippet in the JSON-LD Playground. Maybe good to follow the example...

The other thing the JSON-LD specs do is to validate, both syntactically and semantically, the examples to make sure that different variations actually said the same thing. This is done using a GitHub action. To many specs end up having syntax issues in their examples.

2023-04-12 10:13 UTC, iherman commented
> Since this PR is only about JSON Schema, is it perhaps ok that the JSON-LD is wrong, 

you mean "ok" for now, right?

> but I would like a separate issue filed to ensure that the JSON-LD is corrected in the future.

+1

2023-04-17 20:21 UTC, mprorock requested changes
I have no opposition to adding correct links into examples, etc.  I would however like all examples to reflect workable examples with correct URLs to prevent developer confusion, especially as we move to CR - I would like to see this PR merge change requests from @OR13 and get in so that we can move forward with less broken items and then add more work back in.

2023-04-17 20:25 UTC, decentralgabe commented
I'd like to restate my earlier comment
>  ... the changes I made are copies of the examples in the spec itself, so they should not be controversial whatsoever.
> If the spec changes, then this examples are downstream and should be updated. This is not the place to discuss them. As it stands the examples I had are in conflict with the spec.

It is strange to rate hole here instead of on a new issue (#1066) that addresses the root cause of the issue. 

It would be unfit for this PR's scope to be expanded to (1) fix all examples and then (2) update json schema examples 

(1) needs to be done in #1066. It does not seem productive to hold off merging this until _all examples_ are fixed. This PR moves from a broken to a less broken state, even if there are changes to be had for examples.

2023-04-18 18:39 UTC, brentzundel approved these changes

2023-05-03 21:41 UTC, brentzundel commented
@OR13 and @mprorock in light of the discussion on today's call and the closing of #1066 and opening of #1110, are the changes requested here still necessary?

2023-05-04 21:29 UTC, OR13 commented
This PR can be merged after: https://github.com/w3c/vc-data-model/pull/1110

Which makes the examples that are currently not valid RDF, valid RDF.

2023-05-09 18:25 UTC, decentralgabe commented
@OR13 @mprorock since #1110 is merged is this OK to merge too?

2023-05-10 19:33 UTC, mprorock approved these changes

2023-05-10 19:33 UTC, OR13 approved these changes
ignore the change requests

2023-05-10 19:35 UTC, decentralgabe commented
Merging. Dependent PRs addressed, no outstanding conflicts.

2023-05-10 19:35 UTC, merged

2023-05-11 07:43 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-05-10-vcwg#section1-2) on 2023-05-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2.  update json schema to accurately reflect context defn (pr vc-data-model#1064)

_See github pull request [vc-data-model#1064](https://github.com/w3c/vc-data-model/pull/1064)._




**Manu Sporny:** continuing with other PRs: next item "update json schema to accurately reflect context definition".  

**Gabe Cohen:** this is blocked by a PR that's now been merged, which fixed the example context, which should reserve opposition.  

> *Michael Prorock:* +1.

**Orie Steele:** Manu opened a PR an example context that makes it no longer return a 404.  

**Brent Zundel:** The PR has been merged that makes it a 404.  

> *Michael Prorock:* i have approved.

**Orie Steele:** changing to no objection.  

_See github pull request [vc-data-model#1111](https://github.com/w3c/vc-data-model/pull/1111)._




**Gabe Cohen:** can this be merged with 1111?  

> *Michael Prorock:* please!!!!

**Orie Steele:** can be merged this.  

**Michael Prorock:** yes to merge this and with 1111.  

**Brent Zundel:** 1064 should be merged? No opposition. Merge it.  

**Gabe Cohen:** it's merged.  

</details>