Remove broken links
w3c/vc-data-model pull request #1066
Opened 2023-03-15 17:17 UTC by OR13

- relies on issuer defined terms, which is the simplest way to define terms, and does not require the implementer to download several separate JSON-LD context files to make use of the examples in the spec.

2023-03-15 17:48 UTC, decentralgabe approved these changes

2023-03-16 15:46 UTC, msporny requested changes
Objection to the PR, it would make just about every example in the spec use the "undefined terms" property, which would set a bad precedent. 

Alternatives that could achieve consensus are being discussed here:

https://github.com/w3c/vc-data-model/issues/1071

and here:

https://github.com/w3c/vc-data-model/pull/1064#issuecomment-1472127345

It is highly unlikely that there will be consensus to downgrade almost every example in the specification to, what is effectively, a bad practice in general.

2023-03-16 19:01 UTC, OR13 commented
> Objection to the PR, it would make just about every example in the spec use the "undefined terms" property, which would set a bad precedent.

Actually this fixes that problem (which exists in the spec today), it defines the terms using the default vocab.

The current examples are malformed, and this PR is the simplest possible fix them (since if defines their terms using the default context).

> Alternatives that could achieve consensus include:
> 
> 1. Create a "Getting Started" section that outlines how to get started by using the base context, and then layer semantic meaning after the developer has stabilized the terms they want to use.

This does not fix the problem that the examples in the spec are malformed currently.

Happy to address this in a separate PR.

> 2. Use JSON-LD Contexts that are being used in pilot and production settings.

Introduces further bias, and makes the examples in the spec more complicated.

> 3. Upgrade the base context to include terms like "name" and "website", or other generally useful properties for a credential subject, which could then be used in examples.

This seems like maybe a path forward, make the examples simpler, so you don't need context complexity in them.

You can also use the issuer defined terms to achieve this, that is exactly what the current PR does.

> 4. Use JSON-LD Contexts from the VC Specs Directory.

Introduces further bias, and makes the examples in the spec more complicated.

2023-03-17 22:17 UTC, selfissued approved these changes
I agree that all the hyperlinks in our specification should be valid.

2023-04-11 15:46 UTC, OR13 commented
@Sakurann @brentzundel I would like some call time to discuss this and the JSON Schema PR: 

- https://github.com/w3c/vc-data-model/pull/1064

2023-04-17 20:18 UTC, OR13 commented
I am fine with the working group adding links that have consensus back to the examples, we can keep having that conversation here:

https://github.com/w3c/vc-data-model/issues/1071

It seems better to remove broken links first, and then add non broken links back.

The links that are removed are not required and the examples are non normative.

2023-05-03 15:50 UTC, Sakurann approved these changes

2023-05-03 15:51 UTC, Sakurann commented
> It seems to me harder to discover where those broken links were once they're removed, 

why does the WG need to discover old broken links? the one who is interested in fixing it will know where they are

2023-05-03 15:55 UTC, OR13 commented
I'm closing this PR in favor of https://github.com/w3c/vc-data-model/pull/1111/files

2023-05-03 15:55 UTC, closed without merging

2023-05-03 21:35 UTC, brentzundel commented
> I'm closing this PR in favor of https://github.com/w3c/vc-data-model/pull/1111/files

did you mean #1110 ?