Add 'render' hint property to v2 context
w3c/vc-data-model pull request #1068
Opened 2023-03-15 19:22 UTC by dmitrizagidulin

This standalone PR adds the `render` hint property to the VC 2.0 `@context`. (Note: this separate from PR #1035).

The `render` hint allows for linking to, or embedding, issuer display preferences / hints in a flexible manner (see the [Rendering Verifiable Credentials](https://github.com/WebOfTrustInfo/rwot11-the-hague/blob/master/draft-documents/rendering-vcs-snapshot-9-27-22.md) paper from RWOT 11 for more info and examples).

The intention is to add examples of `render` usage to the VC Spec directory.

2023-03-15 21:37 UTC, msporny commented on contexts/credentials/v2
> +          "@container": "@graph"
```suggestion
          "@container": "@graph"
```

Why does `render` point to a different graph?

2023-03-16 21:31 UTC, brentzundel commented
I assume this PR depends on agreement around #1035. I'm not understanding why we would add `render` to the V2 `@context` otherwise.
Is that correct?

2023-03-17 15:56 UTC, dmitrizagidulin commented
> I assume this PR depends on agreement around #1035. I'm not understanding why we would add `render` to the V2 `@context` otherwise. Is that correct?

This is an alternative, lighter-weight proposal to PR #1035 that reserves the term so that extension specifications can use it.

2023-03-17 21:36 UTC, brentzundel commented
without spec text indicating that the term is being reserved, I don't think adding `render` to the `@context` file would be appropriate.

2023-03-17 22:17 UTC, OR13 requested changes
I do not believe we should add the render property to the core v2 context.

2023-03-17 22:20 UTC, selfissued requested changes
I agree with @brentzundel that it's unnecessary to add this property.

2023-03-22 16:16 UTC, Aisp-GitHub commented
Sorry it was a mistaken operation about approving the change on adding render property.

2023-04-06 23:27 UTC, dmitrizagidulin commented
No consensus was able to be reached, closing PR.

2023-04-06 23:27 UTC, closed without merging