Update the credentialStatus example to a real world one.
w3c/vc-data-model pull request #1085
Opened 2023-04-16 20:30 UTC by msporny

This PR updates the credentialStatus example to use the standards-track specification that this group has adopted.

2023-04-17 16:50 UTC, decentralgabe approved these changes
yay real examples

2023-04-17 17:22 UTC, OR13 approved these changes

2023-04-17 18:21 UTC, TallTed requested changes
Small tweaks

2023-04-17 18:21 UTC, TallTed commented on index.html
>  depending on factors such as whether it is simple to implement or if it is
```suggestion
The precise content of the <a>credential</a> status information is determined
by the specific <code>credentialStatus</code> <a>type</a> definition, and varies
depending on factors such as whether it is simple to implement or if it is
```

2023-04-17 18:21 UTC, TallTed commented on index.html
> +object could contain a link to an external document noting whether or not the
```suggestion
readable information will be retrievable from the URL. For example, the
object could contain a link to an external document which notes whether or not the
```

2023-04-17 20:22 UTC, dlongley approved these changes
+1 to @TallTed's suggestions.

2023-04-18 08:46 UTC, Sakurann approved these changes

2023-04-18 18:49 UTC, brentzundel approved these changes

2023-04-21 06:47 UTC, davidlehn commented on index.html
> +    "id": "https://example.edu/credentials/status/3#94567"
```suggestion
    "id": "https://example.edu/credentials/status/3#94567",
```

2023-04-22 15:35 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-04-22 15:35 UTC, merged

2023-04-24 23:59 UTC, davidlehn commented on index.html
> +    "https://w3id.org/vc/status-list/2021/v1"
Did you mean to remove the example context?  There's no v2 (yet), but v1 would still work here:
https://www.w3.org/2018/credentials/examples/v1
Without that context the input will expand the useful domain specific data `UniversityDegreeCredential`, `degree`, `BachelorDegree`, and `name` into the useless generic `https://www.w3.org/ns/credentials/issuer-dependent#` prefixed values.  I think the examples should better show how to create good data and avoid that vocab.