Remove evidence
w3c/vc-data-model pull request #1092
Opened 2023-04-18 16:44 UTC by OR13

Remove proposed term from v2 context

Addresses #1090

2023-04-18 19:36 UTC, msporny requested changes
-1 for the following reasons:

* This term has [already been used](https://w3c.github.io/vc-specs-dir/#evidence) as an extension point in the VC Specifications Directory.
* It only impacts JSON-LD implementations (and the cost is a handful of bytes for a context that is permanently cached and never downloaded).
* There is active interest in this extension point (as evidenced by the discussion on the calls and the registration of an extension specification).

2023-04-19 07:40 UTC, iherman commented
-1, see https://github.com/w3c/vc-data-model/pull/1093#issuecomment-1514232247

2023-04-19 14:07 UTC, OR13 commented
As I stated on the call.

If the working group has agreed to this term, as a normative requirement, it should not be reserved, and it should be defined in the TR AND in the JSON-LD context.

We should avoid bundling non normative stuff into the JSON-LD context, since they are cached, they can be split by normative and non normative easily, and then implementers can more easily signal their intention to use experimental extensions.

2023-04-19 16:18 UTC, dlongley requested changes
-1 This will lead to mistakes because of `@vocab` being in the core context.

2023-04-19 17:17 UTC, David-Chadwick commented
-1 from me also

2023-04-24 12:36 UTC, awoie commented
-1 from my end as well since OIDF eKYC folks are using it.

2023-05-03 21:49 UTC, brentzundel commented
There does not seem to be a path toward consensus that would result in merging this PR.
I am adding the `pending-close` label and will close in 1 week if consensus still seems unlikely.

2023-05-04 21:11 UTC, OR13 commented
I thought we had agreement, that we would be reserving this URL and term name, and not defining it or using it in the v2 spec?

2023-05-13 09:25 UTC, msporny commented
> I thought we had agreement, that we would be reserving this URL and term name, and not defining it or using it in the v2 spec?

Removing the declaration from the v2 context (what this PR dos) is something that we did not have consensus on, and are unlikely to get consensus on it. It's been a week since being marked pending close. Closing.

2023-05-13 09:25 UTC, closed without merging