Clarify proof section
w3c/vc-data-model pull request #1106
Opened 2023-04-27 22:59 UTC by brentzundel

This PR makes minor normative changes to the proof section.
It renames the section to indicate that the focus is on Securing VCs.
It rewords the introduction to focus on securing rather than proofs.
It clarifies the normative possibilities around the proof property to better reflect the way it is actually used.

fixes #1104

2023-04-27 23:06 UTC, decentralgabe approved these changes
I like *securing*!

2023-04-28 00:04 UTC, selfissued approved these changes
This is clearer than the text that it replaces.

2023-04-28 12:42 UTC, msporny approved these changes

2023-04-28 13:32 UTC, TallTed requested changes
A small tweak. Otherwise, strongly in favor of this PR!

2023-04-28 13:32 UTC, TallTed commented on index.html
> +Credential Data Integrity [[VC-DATA-INTEGRITY]].
It's important to make external document titles distinct from the body text which includes them.
```suggestion
<em>Securing Verifiable Credentials using JSON Web Tokens</em> [[VC-JWT]] specification.
An <dfn>embedded proof</dfn> is a mechanism where the proof is included in the
data model, such as a Data Integrity Proof, which is elaborated on in <em>Verifiable
Credential Data Integrity</em> [[VC-DATA-INTEGRITY]].
```

2023-04-28 14:30 UTC, OR13 approved these changes
Excellent PR.

2023-04-28 16:42 UTC, dlongley approved these changes
Thanks! +1 to @TallTed's suggestion and I have one minor clarifying one of my own.

2023-04-28 16:42 UTC, dlongley commented on index.html
> +this data model, such as a JSON Web Token, which is elaborated on in the
I got just slightly hung up on the language here. The JWT is the wrapper so I think adding "via" here helps make clear what the "such as" applies to.

```suggestion
this data model, such as via a JSON Web Token, which is elaborated on in the
```

2023-05-01 14:43 UTC, TallTed approved these changes

2023-05-04 15:37 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-05-04 15:38 UTC, merged