Remove script breaking echidna
w3c/vc-data-model pull request #1146
Opened 2023-06-07 18:04 UTC by OR13

See https://github.com/w3c/vc-data-model/issues/1145

2023-06-07 20:03 UTC, andresuribe87 approved these changes

2023-06-08 19:15 UTC, msporny requested changes
-1, this PR removes the script that generates all the proofs for DI and JWTs. Without this script executing, we won't have complete examples in the spec anymore. 

The title of this PR is also misleading because we've been generating examples for years with this script and it hasn't been breaking echidna. Can you please point to the echinda failures so we can debug what's going on?

@andresuribe87 can you please clarify why you are approving a PR that removes all examples of external and embedded proofs from the specification? Were you aware that this is what this PR is doing?

2023-06-11 23:03 UTC, msporny commented
Fixed in https://github.com/w3c/vc-data-model/commit/2b71bace9508204f795c1780183e541c78cab1e2

Echidna publishing is showing green: https://github.com/w3c/vc-data-model/actions/runs/5237910786/jobs/9456379183

Confirmed with a new TR-space publication: https://www.w3.org/TR/2023/WD-vc-data-model-2.0-20230611/

This PR should be closed as the root cause has been fixed now.

As an aside, the root cause was respec-vc doing exactly what it's supposed to do and detecting an error when digitally signing using Data Integrity (the documents were malformed based on the old examples/v2 context)... which stops Echidna from publishing examples that respec-vc believes are malformed. An update of respec-vc to the newest examples/v2 context fixed the signing stuff again, and thus Echidna was clear to publish the spec again.

2023-06-13 17:27 UTC, closed without merging

2023-06-14 07:15 UTC, iherman commented
> Closing the PR, @iherman will this tooling survive CR / PR or is this just a temporary thing?

If you ask whether the echidna script will survive CR, the answer is no. Publishing a PR as well as a Rec remains under strict control at W3C, i.e., check and approval from management.

(There are discussions about extending the role for echidna into that range as well, but that is just a possible future trend, not for now).