Add section on media type leniency.
w3c/vc-data-model pull request #1189
Opened 2023-07-08 20:27 UTC by msporny

This PR attempts to address issue #1015 and #1040 by adding guidance on being lenient when processing media types. It does not go as far as providing normative guidance (as there are many correct ways to do content sniffing, and we probably don't want to suggest one way to do it unless we're really, really sure about it being the only correct way).

2023-07-09 21:01 UTC, dlongley requested changes

2023-07-09 21:01 UTC, dlongley commented on index.html
> +top-level `type` field containing a `VerifiablePresentation` element.
```suggestion
top-level `type` field containing a `VerifiablePresentation` element. Additional
subsequent checks are still expected to be performed (according to this
specification) to ensure the payload expresses a conformant Verifiable Presentation.
```

2023-07-09 21:01 UTC, dlongley commented on index.html
> +top-level `type` field containing a `VerifiableCredential` element.
```suggestion
top-level `type` field containing a `VerifiableCredential` element. Additional
subsequent checks are still expected to be performed (according to this
specification) to ensure the payload expresses a conformant Verifiable Credential.
```

2023-07-10 15:10 UTC, TallTed requested changes
These relatively minor tweaks are all based on @dlongley's excellent suggestions.

2023-07-10 15:10 UTC, TallTed commented on index.html
> +liberal in what their applications accept from other systems.
```suggestion
Whenever possible, implementers are advised to use the most precise (the highest
precision) media type for all payloads defined by this specification.
Implementers are also advised to recognize that a payload tagged with a lower
precision media type does not mean that the payload does not meet the rules
necessary to tag it with a higher precision type. Similarly, a payload tagged
with a higher precision media type does not mean that the payload will meet the
requirements associated with the media type. Receivers of payloads, regardless
of their associated media type, are expected to perform appropriate checks to
ensure that payloads conform with the requirements for their use in a given
system.
```

2023-07-10 16:16 UTC, OR13 approved these changes
this looks good, I don't have strong opinions on the suggestions

2023-07-11 04:30 UTC, iherman approved these changes
Thanks to @dlongley and @TallTed for the text improvements.

2023-07-11 14:07 UTC, brentzundel approved these changes

2023-07-11 15:49 UTC, dlongley approved these changes

2023-07-11 16:02 UTC, TallTed approved these changes

2023-07-11 16:06 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-11-vcwg-special#section1-10) on 2023-07-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.10. Add section on media type precision. (pr vc-data-model#1189)

_See github pull request [vc-data-model#1189](https://github.com/w3c/vc-data-model/pull/1189)._




**Brent Zundel:** add section on media type precision. Some change requests.  
… P.R adds guidance for implementers and users of spec for what they may do if they encounter diff media type / content.  
… minimal processing guidelines to determine if contents conforms with VCDM.  

**Dave Longley:** changes are applied. Approved now.  

**Ted Thibodeau Jr.:** appears to be same. Will double check but think it is ready to go.  

**Ivan Herman:** wondering whether it is appropriate to be as a normative section. This is guidelines for implementers.  

**Brent Zundel:** note there is no normative language in the P.R.  

**Ivan Herman:** yeah but there is an algorithm. Normative sounding text.  
… Not just about the SHOULD or MUST etc.  
… not saying I am opposed, just asking the question.  

**Brent Zundel:** any concrete changes?  

**Ivan Herman:** changes would be to make it clearly informative. But just asking question currently.  

</details>

2023-07-11 16:10 UTC, iherman commented
As commented on the call: I wonder whether it is a good idea to put this section as normative. These are guidelines, which sound informative. I feel slightly uncomfortable with these being normative.

Not a strong objection, and if the decision to go ahead with a normative section, I won't oppose.

2023-07-12 16:19 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-07-11-vcwg-special#section1-10) on 2023-07-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.10. Add section on media type precision. (pr vc-data-model#1189)

_See github pull request [vc-data-model#1189](https://github.com/w3c/vc-data-model/pull/1189)._




**Brent Zundel:** add section on media type precision. Some change requests.  
… P.R adds guidance for implementers and users of spec for what they may do if they encounter diff media type / content.  
… minimal processing guidelines to determine if contents conforms with VCDM.  

**Dave Longley:** changes are applied. Approved now.  

**Ted Thibodeau Jr.:** appears to be same. Will double check but think it is ready to go.  

**Ivan Herman:** wondering whether it is appropriate to be as a normative section. This is guidelines for implementers.  

**Brent Zundel:** note there is no normative language in the P.R.  

**Ivan Herman:** yeah but there is an algorithm. Normative sounding text.  
… Not just about the SHOULD or MUST etc.  
… not saying I am opposed, just asking the question.  

**Brent Zundel:** any concrete changes?  

**Ivan Herman:** changes would be to make it clearly informative. But just asking question currently.  

</details>

2023-07-14 19:59 UTC, msporny commented on index.html
> +        <section>
```suggestion
        <section class="informative">
```

2023-07-14 20:03 UTC, msporny commented
> As commented on the call: I wonder whether it is a good idea to put this section as normative. 

The section was supposed to be informative (it contained no normative text, on purpose), and I've marked the informative nature clearly in this PR:

https://github.com/w3c/vc-data-model/pull/1189/commits/9799e5c15c0d443e5a2b59af5ce0056aef931e29

A future PR could try to make the algorithm normative or some of the guidance normative, but for now, it doesn't.

2023-07-14 20:03 UTC, msporny commented
Editorial (but substantive), multiple reviews, changes requested and made, no objections, merging.

2023-07-14 20:03 UTC, merged