Add aud registered claim to v2 context
w3c/vc-data-model pull request #1223
Opened 2023-08-02 21:39 UTC by OR13

```json
{
  "@context": {
      "aud": {
      "@id": "https://www.iana.org/assignments/jwt#aud",
      "@type": "@id"
    }
  },
  "@id": "urn:uuid:123",
  "aud": ["urn:uuid:456", "https://api.example/verifier"]
}
```

```
<urn:uuid:123> <https://www.iana.org/assignments/jwt#aud> <https://api.example/verifier> .
<urn:uuid:123> <https://www.iana.org/assignments/jwt#aud> <urn:uuid:456> .

```

2023-08-02 23:12 UTC, decentralgabe approved these changes

2023-08-03 13:01 UTC, mprorock approved these changes

2023-08-03 22:33 UTC, dmitrizagidulin approved these changes

2023-08-04 01:39 UTC, msporny requested changes
PR includes commits on main, needs a rebase.

2023-08-04 12:55 UTC, OR13 commented on contexts/credentials/v2
> +          "@type": "@id"
```suggestion
```

2023-08-04 12:55 UTC, OR13 commented on index.html
> +processing rules outlined by each associated <code>credentialSchema</code>
```suggestion
```

2023-08-04 12:56 UTC, OR13 commented on index.html
> +            </tr>
```suggestion
```

2023-08-04 12:57 UTC, OR13 commented on index.html
> +A property used for specifying one or more methods to render a credential into a visual,
```suggestion
A property used for specifying how to render a credential into a visual,
```

2023-08-04 12:58 UTC, OR13 commented on index.html
> +
```suggestion
```

2023-08-04 14:42 UTC, davidlehn requested changes
Extraneous commits should be removed so only the single relevant commit remains.

2023-08-04 14:47 UTC, OR13 commented
@davidlehn see same comment on https://github.com/w3c/vc-data-model/pull/1219#issuecomment-1665731653

2023-08-07 21:27 UTC, brentzundel approved these changes

2023-08-07 21:28 UTC, brentzundel commented
@msporny and @davidlehn since this PR is quite simple (and the changes made were all by a single author) I think it should be fine to squash and merge back down to a single commit.

2023-08-09 23:45 UTC, msporny approved these changes

2023-08-09 23:46 UTC, msporny commented
Normative, multiple reviews, no changes requested, no objections, merging.

2023-08-09 23:53 UTC, merged