Editorial update index.html: use JsonSchema and not JsonSchema2023
w3c/vc-data-model pull request #1225
Opened 2023-08-03 08:55 UTC by iherman

This is just a leftover of the naming/versioning change around JSON Schemas.

(Editorial change, only in the examples).

2023-08-03 16:24 UTC, decentralgabe commented on index.html
> +`-01-01T00:00:00Z`), regardless of whether the system in question
```suggestion
`2023-01-01T00:00:00Z`), regardless of whether the system in question
```

2023-08-03 16:24 UTC, decentralgabe approved these changes
thanks!

2023-08-03 16:35 UTC, andresuribe87 approved these changes

2023-08-03 17:48 UTC, OR13 approved these changes
Assuming suggestions are applied

2023-08-04 00:16 UTC, dmitrizagidulin approved these changes
(The Ecosystem Compatibility section seems to be an artifact of stray commit history)

2023-08-04 01:40 UTC, msporny requested changes
PR includes commits on main, needs a rebase.

2023-08-04 04:04 UTC, iherman commented
> PR includes commits on main, needs a rebase.

@msporny I do not understand this remark. Rebase on what?

2023-08-04 11:57 UTC, msporny commented
> @msporny I do not understand this remark. Rebase on what?

Look at the file diff... it contains your changes and a bunch of changes on an invalid branch on main. There was a PR that was pulled in a few days ago (the Ecosystem Compatability PR) that destroyed history, so I had to re-create history on main and force push to main, which then caused this PR (and many others) to have issues. To rebase:

```
git checkout main
git pull
git checkout iherman-patch-1
git rebase main
```

^^ That might do the trick, or you might have conflicts you need to resolve.

I can also squash-merge, but the current diff is probably going to confuse people that are reviewing, and they'll start suggesting changes to things that were not in this PR.

2023-08-04 15:23 UTC, iherman commented
Moving over to #1229

2023-08-04 21:04 UTC, TallTed commented
> Moving over to https://github.com/w3c/vc-data-model/pull/1229; this PR should be closed without merge.

As with #1226, maybe change title so people don't get drawn down the glitch rabbit hole?

2023-08-07 21:40 UTC, brentzundel commented
When #1229 is merged, this PR should be closed.

2023-08-09 10:24 UTC, awoie requested changes
contains ecosystem compatibility which imo is not desired

2023-08-09 16:35 UTC, brentzundel commented
@awoie this PR has been superseded by #1229 and will be closed when that PR is merged.

2023-08-09 23:57 UTC, msporny commented
Merged via #1229, closing.

2023-08-09 23:57 UTC, closed without merging