Update links from VC-JWT to VC-JOSE-COSE
w3c/vc-data-model pull request #1234
Opened 2023-08-09 16:11 UTC by andresuribe87

Fixes #1233

***
<a href="https://pr-preview.s3.amazonaws.com/andresuribe87/vc-data-model/pull/1234.html" title="Last updated on Aug 20, 2023, 7:20 PM UTC (97bdc05)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1234/6d626f8...andresuribe87:97bdc05.html" title="Last updated on Aug 20, 2023, 7:20 PM UTC (97bdc05)">Diff</a>

2023-08-09 16:14 UTC, decentralgabe approved these changes

2023-08-09 16:41 UTC, brentzundel approved these changes

2023-08-10 03:19 UTC, TallTed requested changes
Small tweak for clarity

2023-08-10 03:19 UTC, TallTed commented on index.html
> +JOSE or COSE [[VC-JOSE-COSE]] and Data Integrity Proofs [[VC-DATA-INTEGRITY]] and a variety of cryptographic
```suggestion
JOSE or COSE [[VC-JOSE-COSE]], Data Integrity Proofs [[VC-DATA-INTEGRITY]], and a variety of cryptographic
```

2023-08-14 20:48 UTC, decentralgabe commented
there are some other references to vc-jwt that should be updated like the text here https://github.com/w3c/vc-data-model/blob/main/index.html#L4050 and here https://github.com/w3c/vc-data-model/blob/main/index.html#L583

2023-08-14 21:01 UTC, TallTed commented
@decentralgabe -- I think https://github.com/w3c/vc-data-model/blob/main/index.html#L583 moved to https://github.com/w3c/vc-data-model/blob/main/index.html#L591

2023-08-14 21:08 UTC, andresuribe87 commented
> there are some other references to vc-jwt that should be updated like the text here https://github.com/w3c/vc-data-model/blob/main/index.html#L4050 and here https://github.com/w3c/vc-data-model/blob/main/index.html#L583

Both changes were already captured. I've merged from main so you can see the same lines.

2023-08-15 14:54 UTC, OR13 approved these changes

2023-08-15 22:21 UTC, dlongley approved these changes

2023-08-15 22:21 UTC, shigeya approved these changes

2023-08-16 05:41 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-15-vcwg-special#section1-5) on 2023-08-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.5. Update links from VC-JWT to VC-JOSE-COSE (pr vc-data-model#1234)

_See github pull request [vc-data-model#1234](https://github.com/w3c/vc-data-model/pull/1234)._




**Brent Zundel:** next PR: 1234 Update links from VC-JWT to VC-JOSE-COSE. request for changes from Ted. believe they've been addressed.  

**Gabe Cohen:** A note that Ted's comments were resolved, I think we're good to merge this.  

</details>

2023-08-20 19:20 UTC, msporny approved these changes

2023-08-20 19:20 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-08-20 19:21 UTC, merged