Vocabulary fixes — replacement of #1241
w3c/vc-data-model pull request #1253
Opened 2023-08-21 07:45 UTC by iherman

This is actually a replacement of #1241 : it includes all the changes in there, plus the missing pieces in https://github.com/w3c/vc-data-model/pull/1241#issuecomment-1685780129.

Making PR on top of #1241 would have led to problems because, in the meantime, the main branch has changed too much (e.g., the diagrams have been added), so it was simpler to create a PR on top of `main` rather than `fix/vocab-issues`

2023-08-21 11:53 UTC, OR13 commented
This PR does not include the correction to credential graph. A credential graph is not a credential.

2023-08-21 14:01 UTC, iherman commented
> This PR does not include the correction to credential graph. A credential graph is not a credential.

The vocabulary file on the `main` branch already has this change:

https://github.com/w3c/vc-data-model/blob/03b0d90b5d7c7ad24e39320b82a4ada32fe0d8d1/vocab/credentials/v2/vocabulary.yml#L64

2023-08-21 14:23 UTC, decentralgabe approved these changes
@iherman should this include https://github.com/w3c/vc-json-schema/issues/206 as well?

2023-08-21 16:11 UTC, andresuribe87 approved these changes

2023-08-21 16:40 UTC, OR13 requested changes
@iherman can you please update the label for this section of the vocabulary? That is the change that is not carried over from the previous PR![Screenshot_20230821-123925.png](https://github.com/w3c/vc-data-model/assets/8295856/aad0ff41-a33b-44ce-8a1e-92168a8bec13)

2023-08-22 06:25 UTC, iherman commented
> @iherman can you please update the label for this section of the vocabulary? That is the change that is not carried over from the previous PR!
> [Screenshot_20230821-123925.png](https://user-images.githubusercontent.com/8295856/262088691-aad0ff41-a33b-44ce-8a1e-92168a8bec13.png)

Oops, sorry. I mixed it up. Done.

2023-08-22 06:26 UTC, iherman commented
> Similarly for the credential graph label... The labels should distinguish the concepts. It's not helpful to call everything simply a "verifiable credential"... When it could be a set of separate credential graphs or a Verifiable Credential that is not a Verifiable Credential Graph.

I do not understand what you want to say. Is there a change you propose in the vocab file? If so, can you put that explicitly in the comment?

2023-08-22 14:55 UTC, OR13 commented on vocab/credentials/v2/vocabulary.yml
> +    label: Verifiable credential graph
this was the change I was looking for.

2023-08-22 14:56 UTC, OR13 approved these changes

2023-08-22 14:58 UTC, OR13 commented on vocab/credentials/v2/vocabulary.yml
> +    label: Verifiable credential graph
@iherman I was doing code reviews from my phone, its possible I missed this in your original PR.

The general comment was to address the labels and try to provide unique language that distinguished all the various "verifiable credential" labels.

It seems like my feedback has been addressed.

2023-08-22 15:51 UTC, dlongley approved these changes

2023-08-22 15:51 UTC, seabass-labrax approved these changes

2023-08-22 15:52 UTC, seabass-labrax commented
I agree with the discussion in the 2023-08-22 meeting that this PR is substantially similar to @iherman's earlier PR and so should inherit that PR's approvals.

2023-08-27 23:23 UTC, msporny approved these changes

2023-08-27 23:25 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-08-27 23:25 UTC, merged