Issue 1118
w3c/vc-data-model pull request #1257
Opened 2023-08-24 21:35 UTC by brentzundel

This PR fixes #1118 

This PR adds language to the media types section about accept headers and content types.

It is most certainly not entirely correct or sufficient, but hopefully can serve as a starting point to bring in the ideas discussed in #1118.

2023-08-24 22:45 UTC, mprorock approved these changes

2023-08-25 01:42 UTC, TallTed requested changes

2023-08-25 01:42 UTC, TallTed commented on index.html
> +used when indicating content types.
```suggestion
<a>verifiable credentials</a> in accept headers and
when indicating content types.
```

2023-08-25 16:06 UTC, decentralgabe approved these changes

2023-08-26 13:39 UTC, OR13 commented on index.html
> +<a>verifiable credentials</a> in accept headers and
```suggestion
<a>verifiable credentials</a> and <a>verifiable presentations</a> in accept headers and
```

2023-08-26 13:45 UTC, OR13 commented on index.html
> +          </p>
```suggestion
          </p>
          <p>
HTTP servers might ignore the accept header and return another content type, or return an error code such as <a data-cite="RFC7231#section-6.5.13">415 Unsupported Media Type</a>.
          </p>
```

2023-08-28 14:54 UTC, OR13 commented on index.html
> +          </p>
I suggest taking this phrasing instead of mine.

2023-08-29 20:28 UTC, msporny approved these changes

2023-08-29 22:20 UTC, dlongley approved these changes

2023-08-29 22:20 UTC, TallTed approved these changes

2023-08-31 21:57 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-08-31 21:57 UTC, merged

2023-09-03 08:41 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-08-29-vcwg-special#section1-4) on 2023-08-29

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4.  (pr vc-data-model#1257)

_See github pull request [vc-data-model#1257](https://github.com/w3c/vc-data-model/pull/1257)._




**Manu Sporny:** describes use in HTTP, specifically appropriate use of media types. However, be liberal in what you accept.  

</details>