Adding the jsonSchema property to the vocabulary
w3c/vc-data-model pull request #1268
Opened 2023-09-06 13:01 UTC by iherman

This is the counterpart, in the VCDM vocabulary, of https://github.com/w3c/vc-json-schema/pull/211. The diagram, and its alt-text description, has also been adapted.

See the [preview of the generated vocab](https://w3c.github.io/yml2vocab/previews/vcdm/vocabulary.html)

2023-09-06 15:07 UTC, decentralgabe approved these changes

2023-09-06 18:30 UTC, TallTed requested changes
Substantial tweaks to the diagram description, trying to make the language and presentation order consistent throughout, so it will be easier for a visually impaired person, for instance, to consume via an enunciator. Also switched some en-uk to en-us, to conform with W3 style. There may be additional changes needed, which will be much easier to see and request once all current change requests have been acted upon.

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
>            The "VerifiableCredential" ellipse is connected through a connecting line
Note that this deletes line 270, which is replaced in the suggestion below, to work around GitHub change request limitations.
```suggestion
```

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
>            "issuer", "evidence", "refreshService", "renderMethod", and "confidenceMethod" boxes.
Note that this includes what was line 270, which was deleted above, to work around GitHub change request limitations.
```suggestion
          The "VerifiableCredential" ellipse is connected to the "credentialSchema", "credentialStatus",
          "credentialSubject", "issuer", "evidence", "refreshService", "renderMethod", and "confidenceMethod"
          boxes, through connecting lines styled as Domain Of. 
```

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
>            The OR box is connected to the "termsOfUse", "validFrom", and "validUntil" boxes with a connecting line styled as Domain.
```suggestion
          The crossing point circle is connected to the "termsOfUse", "validFrom", and "validUntil" boxes with a connecting line styled as Domain Of.
```

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
>            The ellipse "JsonSchemaCredential" is connected to the ellipse labelled "VerifiableCredential" with a
```suggestion
          The "JsonSchemaCredential" ellipse is connected to the "VerifiableCredential" ellipse with a 
```

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
> +          to the "VerifiableCredential" ellipse.
```suggestion
          Finally, the "VerifiableCredentialGraph" ellipse is connected to the "VerifiableCredential"
          ellipse with a connector line styled as Contains.
```

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
>            On the right hand side of the column there is an extra column of ellipses styled as "Class", and labeled as "CredentialSchema",
```suggestion
          On the right side of the column, there is another column of ellipses, styled as "Class", and labeled as "CredentialSchema",
```

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
> +          to a Datatype Shape labeled as "rdf:JSON".
```suggestion
          Finally, the "CredentialSchema" ellipse is connected to one more ellipse, on the far right
          side of the diagram, styled as Class and labeled as "JsonSchema", with a connecting line
          styled as Superclass. This "JsonSchema" ellipse is also connected to a Property box
          labeled as "jsonSchema", through a connector line styled as Domain Of. This "jsonSchema"
          box is connected to a Datatype shape labeled as "rdf:JSON", with a connecting line
          styled as Range. 
```

2023-09-06 18:30 UTC, TallTed commented on vocab/credentials/v2/template.html
>            ellipses, respectively.
```suggestion
          "refreshService", "renderMethod", "confidenceMethod", and "termsOfUse" are respectively
          connected to those Class ellipses, with connecting lines styled as Range. 
```

2023-09-07 02:11 UTC, OR13 approved these changes

2023-09-07 11:22 UTC, iherman commented
Thanks, @TallTed. I was hoping you would do that...

(It is hard to create those descriptions...)

2023-09-07 17:54 UTC, TallTed approved these changes

2023-09-13 10:44 UTC, merged

2023-09-13 10:44 UTC, decentralgabe commented
Multiple editorial reviews, changes accepted, over a week. Merging.