Add base classes and fragment identifiers for vocabulary.
w3c/vc-data-model pull request #1272
Opened 2023-09-10 13:48 UTC by msporny

This PR attempts to address part of issue #1263 by defining base classes (and their anchors) in the VCDM specification.

2023-09-11 04:30 UTC, iherman reviewed
Would it be possible to, in the same PR, make the changes on the vocabulary.yml file, too? For each of those classes a `defined_by` statement should replace the comment field.... This would save us yet another PR/merge round.

(I can make a PR against this one if you prefer.)

2023-09-11 12:08 UTC, TallTed requested changes

2023-09-11 12:08 UTC, TallTed commented on index.html
> +Candidate Recommendation phase.</span>
```suggestion
Serves as a superclass for specific evidence types that are placed into the
<a href="#evidence">evidence</a> property. <span class="issue atrisk">This
superclass is at risk and will be removed if at least two independent
implementations for the superclass are not identified by the end of the
Candidate Recommendation phase.</span>
```

2023-09-11 12:08 UTC, TallTed commented on index.html
> +and other specifications that benefit from the definition of base classes:
```suggestion
and other specifications that benefit from such definitions:
```

2023-09-11 12:08 UTC, TallTed commented on index.html
> +Serves as a supercass for specific schema types that are placed into the
```suggestion
Serves as a superclass for specific schema types that are placed into the
```

2023-09-11 12:08 UTC, TallTed commented on index.html
> +Serves as a supercass for specific credential status types that are placed into
```suggestion
Serves as a superclass for specific credential status types that are placed into
```

2023-09-11 12:08 UTC, TallTed commented on index.html
> +by the end of the Candidate Recommendation phase.
```suggestion
Serves as a superclass for specific confidence method types that are placed into
the `confidenceMethod` property.
<span class="issue atrisk">This superclass is at risk and will be removed if
at least two independent implementations for the superclass are not identified
by the end of the Candidate Recommendation phase.
```

2023-09-11 12:08 UTC, TallTed commented on index.html
> +</span>
```suggestion
Serves as a superclass for specific refresh service types that are placed into
the <a href="#refreshing">credentialRefresh</a> property.
<span class="issue atrisk">This superclass is at risk and will be removed if
at least two independent implementations for the superclass are not identified
by the end of the Candidate Recommendation phase.
</span>
```

2023-09-11 12:08 UTC, TallTed commented on index.html
> +by the end of the Candidate Recommendation phase.
```suggestion
Serves as a superclass for specific render method types that are placed into
the `renderMethod` property.
<span class="issue atrisk">This superclass is at risk and will be removed if
at least two independent implementations for the superclass are not identified
by the end of the Candidate Recommendation phase.
```

2023-09-11 12:08 UTC, TallTed commented on index.html
> +by the end of the Candidate Recommendation phase.
```suggestion
Serves as a superclass for specific terms of use types that are placed into
the <a href="#terms-of-use">termsOfUse</a> property.
<span class="issue atrisk">This superclass is at risk and will be removed if
at least two independent implementations for the superclass are not identified
by the end of the Candidate Recommendation phase.
```

2023-09-11 16:00 UTC, OR13 approved these changes

2023-09-12 14:55 UTC, dlongley approved these changes

2023-09-13 04:57 UTC, iherman commented
> Would it be possible to, in the same PR, make the changes on the vocabulary.yml file, too? For each of those classes a `defined_by` statement should replace the comment field.... This would save us yet another PR/merge round.
> 
> (I can make a PR against this one if you prefer.)

Putting my money where my mouth is... I have created #1278 to do this.

@msporny, if you are o.k. with this, the best would be to merge #1278 right away into this one, so that all the possible comments would be at one place. I just did not want to directly edit your PR.

2023-09-13 10:46 UTC, decentralgabe approved these changes

2023-09-14 08:05 UTC, David-Chadwick approved these changes

2023-09-15 05:55 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section1-6) on 2023-09-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.6. Add base classes and fragment identifiers for vocabulary. (pr vc-data-model#1272)

_See github pull request [vc-data-model#1272](https://github.com/w3c/vc-data-model/pull/1272)._




**Brent Zundel:** primarily editorial, raised a few days ago.  

**Manu Sporny:** Yes to all of that, just need to merge TallTed's changes.  

_See github pull request [vc-data-model#1278](https://github.com/w3c/vc-data-model/pull/1278)._




**Ivan Herman:** For the record, I did 1278 yesterday.  
� it's on top of 1272.  

**Manu Sporny:** agree to merge on top of it.  

**Brent Zundel:** merged, back to 1272.  
� still have 3 more days for reviews.  
� manu to look at suggestions made, anticipating that the PR will be merged soon.  

> *Sebastian Crane:* What I was saying is that the ease of merging Ivan's PR illustrates how useful it is to push to a 'personal' branch within the W3C repository, not to your GitHub fork. It is not possible to push to someone else's GitHub fork, so that discussion would have involved lots of git commands if Manu hadn't pushed to the main repository.

</details>

2023-09-26 20:41 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-09-26 20:41 UTC, merged