removes ToU from the main text while keeping it in the reserved extension points table
w3c/vc-data-model pull request #1294
Opened 2023-09-26 23:19 UTC by Sakurann

addresses issue #1010 - there does not seem to be sufficient interest to better define Terms of Use property in the main text. 
but keeping it in the reserved extension points table.

2023-09-27 18:00 UTC, decentralgabe approved these changes

2023-10-04 14:46 UTC, brentzundel approved these changes

2023-10-06 18:24 UTC, David-Chadwick commented
I suggest that this PR is closed due to #1295

2023-10-07 15:36 UTC, RolandoMorales22 approved these changes

2023-10-16 02:50 UTC, msporny requested changes
Suggest that we close this PR since PR #1295 has overtaken it.

2023-10-17 16:07 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-10-17-vcwg-special#section2-5) on 2023-10-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.5. removes ToU from the main text while keeping it in the reserved extension points table (pr vc-data-model#1294)

_See github pull request [vc-data-model#1294](https://github.com/w3c/vc-data-model/pull/1294)._




**Brent Zundel:** The plan as we discussed last time, is to close 1294 assuming we get consensus and can merge 1295.  
… I'm going to mark it as pending close.  
… The discussion continues in 1295.  

> *Manu Sporny:* +1 to that path forward.

</details>

2023-10-26 00:51 UTC, closed without merging