Align JWT/JWS fields with IETF RFCs.
w3c/vc-data-model pull request #1325
Opened 2023-10-23 00:13 UTC by msporny

This PR attempts to address issue #1275 by aligning the JSON-LD Context definitions in the base context with the IETF JOSE RFCs. The PR does this by allowing `kid`, `iss`, `sub`, and `aud` to be strings (they were previously limited to only being URLs).

2023-10-23 00:14 UTC, dlongley approved these changes

2023-10-23 00:37 UTC, selfissued approved these changes

2023-10-23 06:51 UTC, iherman approved these changes

2023-10-23 18:04 UTC, decentralgabe approved these changes

2023-10-24 13:31 UTC, OR13 requested changes
This breaks the Verifiable Credential Graph as described in the data model.

It causes edges and nodes to be formed in RDF that are not as the issuer, holder, verifier expects when reading the specification, and it destroys conceptual alignment with data integrity.

2023-10-25 00:17 UTC, peacekeeper commented
> This breaks the Verifiable Credential Graph as described in the data model.

@OR13 I'm curious if your concern is about changing the definition of the terms to allow strings, or if it is about about having them in the context at all?

2023-10-25 00:37 UTC, OR13 commented
My concern is that 'iss' and 'issuer' are both identifiers that can be nodes or edges in RDF.

In general, the purpose of a shared graph data model is to be able to reason consistently from analyzing large data sets.

For example all identifiers that attempted to purchase alcohol from a specific location.

Both the location and the identifier for the subject will show up in the graph, regardless of the RDF shape.

In the case that you wanted to analyze related key material or other commonly understood claims, you would want them to have a specific shape in RDF, and then count occurrences, or apply other more advanced graph algorithms.

I don't think it's a good idea to make these claims not work correctly for JOSE or COSE but have them work correctly for data integrity proofs.

This applies to how proofs connect verifiable credentials to controller documents, or other identity representations.

However, in the case that there were no mapping in the common context, perhaps it's possible that a proprietary mapping might occur, and become the industry standard for analyzing JOSE or COSE data sets as RDF graphs.

Transmute will formally object if the information model is positioned to make analysis of a specific securing mechanism less intuitive or useful in the final technical recommendation.

However, Transmute would not object, if the working group was instead only focused on defining a single securing mechanism, and making that securing mechanism favorable to graph analysis.

2023-10-25 07:03 UTC, iherman commented
> My concern is that 'iss' and 'issuer' are both identifiers that can be nodes or edges in RDF.
> 

I am not sure I understand, @OR13, as I have the question as @peacekeeper.

The statement above is correct. The problem is that there is a subtle difference between the semantics of the two properties: the object in the corresponding triples can be a literal for `iss` and can only be a bona fide URL for `issuer`. These are the facts as of today in the model. Nothing is "broken", it just means that the various analysis, that you describe, and that is based on the specification of those properties, must take this fact in account. The change in the context file only encodes this difference.

(Correction, b.t.w.: from a generic RDF point of view it is correct that any property identifier can also identify a node in the graph, but I do not think this is relevant for the VCDM. Both `iss` and `issuer` identify edges of the graph which "point" to objects.)

2023-10-25 12:50 UTC, msporny commented
@OR13 wrote:
> For example all identifiers that attempted to purchase alcohol from a specific location.
> Both the location and the identifier for the subject will show up in the graph, regardless of the RDF shape.

Speaking as an organization that is working on exactly this use case (<a href="https://www.mytruage.org/">TruAge</a>), placing data like this in a VC is an anti-pattern. Tracking of individuals without their consent is an anti-pattern... and even with their consent is a dubious value proposition. So, if this is the use case we're focusing on, I can say that we definitely do not want to enable this sort of ecosystem when it comes to age-gated retail purchases. We should be optimizing for privacy-respecting frameworks.

> In the case that you wanted to analyze related key material or other commonly understood claims, you would want them to have a specific shape in RDF, and then count occurrences, or apply other more advanced graph algorithms.

Yes, agreed. The issue is that JWTs are so general when it comes to what you can put in fields (effectively, any string will do), that you can't count on that behavior. 

> I don't think it's a good idea to make these claims not work correctly for JOSE or COSE but have them work correctly for data integrity proofs.

For some definition of "correctly". The JOSE specifications are clear that the fields listed in this PR are `StringOrURI` and what was there before only allowed `URI`, which meant that the VCWG was changing the definition of JOSE (which we don't have the authority to do).

> Transmute will formally object if the information model is positioned to make analysis of a specific securing mechanism less intuitive or useful in the final technical recommendation.

I expect others would object that we're changing the foundational assumptions of JOSE. In any case, thanks for making your intent to formally object clear.

Here's what I expect to happen when Transmute formally objects: Evidence will be put forward that the VCWG decided to change the definition of JWTs w/o approval from the JOSE community, and with one of the Editor's for that specification (@selfissued) in support of this PR, and the objection will be overruled. 

What I suggest we do in order to get some finality on this issue is to ask the JOSE WG if it's ok if we profile the JWT specification and disallow strings in `kid`, `iss`, `sub`, and `aud`. This would mean that strings are illegal in those places in VC-JWT and you can only use URLs there. If the JOSE WG is ok with that path forward, then we can close this PR and cite that the JOSE WG approved the profiling of JWTs in that way for VCs.

> However, Transmute would not object, if the working group was instead only focused on defining a single securing mechanism, and making that securing mechanism favorable to graph analysis.

-1, we have implementers implementing JOSE-secured VCs and Data Integrity-secured VCs. We need to document both.

2023-10-25 15:35 UTC, longpd approved these changes

2023-10-27 19:21 UTC, decentralgabe requested changes
as terms controlled by the vc-jose-cose work item, I align with @OR13's views, specifically

> It causes edges and nodes to be formed in RDF that are not as the issuer, holder, verifier expects when reading the specification, and it destroys conceptual alignment with data integrity.

The terms must maintain conceptual alignment with data integrity.

2023-10-27 19:22 UTC, selfissued requested changes
The kid, iss, sub, and aud paramters can be (and are) be strings without this PR being merged.

For instance https://cloud.google.com/enterprise-knowledge-graph/docs/overview uses values of these kinds as strings in their knowledge graph.

Orie's objections about this change excluding these terms from the knowledge graph seems to apply.

Therefore, I believe that this PR should be closed without merging.

2023-10-27 20:50 UTC, msporny commented
@decentralgabe wrote:
> The terms must maintain conceptual alignment with data integrity.

Why? vc-cose-jose specifically does not align w/ Data Integrity in so many ways. Why does  `kid`, `iss`, `sub`, and `aud` need to align with Data Integrity over aligning with JOSE?

@selfissued wrote:
> The kid, iss, sub, and aud paramters can be (and are) be strings without this PR being merged.

No, they can't, they'll be converted to URLs without this PR.

If this PR isn't merged, `kid`, `iss`, `sub`, and `aud` will be interpreted as URLs. Full stop. By not accepting this PR, you are profiling JOSE down to require `kid`, `iss`, `sub`, and `aud` to be URLs.

I'm trying to make sure the vc-jose-cose work item doesn't shoot itself in the foot here, but if the Editors of that spec really do mean to make `kid`, `iss`, `sub`, and `aud` to be URLs, I won't stand in the way. 

I'm marking this PR as pending close.

2023-10-28 19:23 UTC, David-Chadwick approved these changes

2023-10-29 19:59 UTC, decentralgabe commented
> @decentralgabe wrote:
> 
> > The terms must maintain conceptual alignment with data integrity.
> 
> Why? vc-cose-jose specifically does not align w/ Data Integrity in so many ways. Why does `kid`, `iss`, `sub`, and `aud` need to align with Data Integrity over aligning with JOSE?

My concern is specifically with `iss` and `sub` since they have direct relation to the core data model. It seems that in constructing the credential graph, being able to show that these terms are closely related is of value. 

Even if a JWS is used there is value in having its properties represented in the graph consistently across securing formats. From my (growing, but limited) understanding of the graph data model, and @OR13's comment (quote below), this is better served with the context as-is. If I have a misunderstanding here - please correct me.

> In the case that you wanted to analyze related key material or other commonly understood claims, you would want them to have a specific shape in RDF, and then count occurrences, or apply other more advanced graph algorithms.

2023-10-29 20:26 UTC, msporny commented
> > @decentralgabe wrote:
> My concern is specifically with `iss` and `sub` since they have direct relation to the core data model. It seems that in constructing the credential graph, being able to show that these terms are closely related is of value.
> 
> Even if a JWS is used there is value in having its properties represented in the graph consistently across securing formats. From my (growing, but limited) understanding of the graph data model, and @OR13's comment (quote below), this is better served with the context as-is. If I have a misunderstanding here - please correct me.

It depends on what you're optimizing for here. There are two mutually exclusive optimizations that can be done with this particular issue:

1. Optimize for graph semantics.
2. Optimize for broad interop w/ JOSE.

By rejecting this PR, you are optimizing for item 1 above. By optimizing for 1, you are profiling `iss` and `sub` as used in JOSE from `StringOrURI` to only allow `URI`. Any string value such as "key-1" will be interpreted as a relative URL instead of a string. So, I expect vc-jose-cose will need some language warning people about always using full URLs or understanding that if they don't, a document-relative URL will be presumed for `iss` and `sub`.

IOW, your understanding is correct, the decision just doesn't align with my understanding that the majority of the JOSE community does not care if the graph semantics match up with other securing mechanisms (or graph semantics in general).

2023-11-01 11:00 UTC, brentzundel commented
Closing, as discussed in the meeting on 31 October.

2023-11-01 11:00 UTC, closed without merging