Add section on Data Theft to Privacy Considerations.
w3c/vc-data-model pull request #1356
Opened 2023-11-18 20:20 UTC by msporny

This PR attempts to address issue #1247 by adding a section on Data Theft, and advising all roles to be careful how much data they store and how long they store it. Advice is given to regulators to play an active role in reducing the collection of PII.

2023-11-18 22:02 UTC, dlongley approved these changes

2023-11-20 02:52 UTC, kdenhartog commented on index.html
> +extracted from hardware devices.
```suggestion
extracted from hardware devices. Furthermore, it's suggested that
<a>Holders<a> hold data at the edge whenever possible in order to
reduce the likelihood of attack.
```

2023-11-20 02:52 UTC, kdenhartog approved these changes
LGTM - small suggestion but just a nit

2023-11-20 05:44 UTC, brianorwhatever approved these changes

2023-11-20 16:23 UTC, longpd approved these changes

2023-11-20 18:11 UTC, decentralgabe approved these changes

2023-11-20 21:51 UTC, TallTed requested changes
Editorial language tweaks

2023-11-20 21:51 UTC, TallTed commented on index.html
> +break into in order to acquire and exchange it for financial gain.
```suggestion
individuals, such as <a>holders</a> and <a>subjects</a>. Storing this data
can create honeypots of sensitive data that attackers are motivated to
break into in order to acquire and exchange that data for financial gain.
```

2023-11-20 21:51 UTC, TallTed commented on index.html
> +<a>Issuers</a> are advised to hold on to the minimum amount of data
```suggestion
<a>Issuers</a> are advised to retain the minimum amount of data
```

2023-11-20 21:51 UTC, TallTed commented on index.html
> +on their data, or large-scale theft if an attack is successful.
```suggestion
<a>Holders</a> are advised to use implementations that appropriately
encrypt their data both in transit and at rest, and protect sensitive
material (such as cryptographic secrets) in ways that cannot be easily
extracted from hardware devices. Furthermore, it is suggested that
<a>holders<a> store and manipulate their data only on devices that they
control, away from centralized systems, to reduce the likelihood of
attack on their data, or large-scale theft if an attack is successful.
```

2023-11-20 21:51 UTC, TallTed commented on index.html
> +transaction and to not hold on to any data beyond the needs of any particular
```suggestion
transaction and to not retain any data beyond the needs of any particular
```

2023-11-20 21:51 UTC, TallTed commented on index.html
> +compliance regimes are operating as expected.
```suggestion
Regulators are advised to rethink audit requirements such that more
privacy-preserving mechanisms can be used to achieve similar levels of
enforcement and audit capabilities. For example, audit-focused regulations
that insist on collection and long-term retention of personally identifiable
information can cause harm to individuals and organizations if that same
information is compromised and accessed by an attacker. The technologies
described by this specification enable <a>holders</a> to more-readily prove
attributes about themselves and others, reducing the need for long-term data
retention by <a>verifiers</a>. Alternatives include keeping logs that the
information was collected and checked, as well as random tests to ensure
that compliance regimes are operating as expected.
```

2023-11-25 23:52 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-11-25 23:52 UTC, merged