Add missing digestMultibase value in base context.
w3c/vc-data-model pull request #1395
Opened 2023-12-18 23:01 UTC by msporny

The current specification notes that whether or not to allow `digestSRI`, `digestMultibase`, or both [will be determined during the Candidate Recommendation phase](https://w3c.github.io/vc-data-model/#integrity-of-related-resources). However, the current context only includes `digestSRI`. This PR adds `digestMultibase` to the base context such that a comparison between the two mechanisms can be made during the CR period.

2023-12-18 23:41 UTC, decentralgabe approved these changes

2023-12-19 08:22 UTC, iherman requested changes

2023-12-19 08:22 UTC, iherman commented on contexts/credentials/v2
> +      "@type": "https://www.w3.org/2018/credentials#multibase"
```suggestion
      "@type": "https://w3id.org/security#multibase"
```

Whether we like it or not, at the moment `multibase` is defined in the Security vocabulary. We may have to remedy this and have these two in the same vocabulary at some point, but that is a discussion for another day (ie, post CR).

2023-12-19 14:51 UTC, iherman approved these changes

2023-12-19 17:21 UTC, andresuribe87 approved these changes

2023-12-19 17:23 UTC, brianorwhatever approved these changes

2023-12-20 07:36 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-12-19-vcwg-special#section2-10) on 2023-12-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.10. Add missing digestMultibase value in base context. (pr vc-data-model#1395)

_See github pull request [vc-data-model#1395](https://github.com/w3c/vc-data-model/pull/1395)._




**Manu Sporny:** Just before next steps, there is one post CR issue that I want to make sure we cover which is #1395 which adds a missing `digestMultibase` value to the base context.  
… The current spec says "for `relatedResource`" that we're looking for feedback for `digestSri` or `digestMultibase`, in order for that to happen we have to enable one or the other or both. One was missing from the context.  
… We have written text saying we expect the context to possibly change and can add/remove as we see fit. Just wanted people to see this.  

**Brent Zundel:** This PR seems straightforward to me.  
… Any comments?  

</details>

2023-12-20 16:34 UTC, dlongley approved these changes

2023-12-20 20:04 UTC, TallTed approved these changes

2023-12-20 21:42 UTC, longpd approved these changes

2023-12-26 15:08 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-12-26 15:08 UTC, merged