update references to public key with verification material
w3c/vc-data-model pull request #1414
Opened 2024-01-18 19:14 UTC by nicksteele

2024-01-18 19:14 UTC, nicksteele commented
Sorry, branch management is hard

2024-01-18 21:07 UTC, TallTed requested changes
tweaked language and crosslinks

2024-01-18 21:07 UTC, TallTed commented on index.html
> +verification material to use for [=verification=] purposes, the revocation
```suggestion
[=verification material=], the revocation 
```

2024-01-18 21:07 UTC, TallTed commented on index.html
> +confirmation of the validity of all verification material before using it.
```suggestion
confirmation of the validity of all [=verification material=] before using it.
```

2024-01-18 21:07 UTC, TallTed commented on index.html
> +verification material metadata related to the [=holder=]. The [=verifier=]
```suggestion
[=verification=] metadata related to the [=holder=]. The [=verifier=]
```

2024-01-18 21:07 UTC, TallTed commented on index.html
> +the verification material used to secure [=verifiable presentations=]. This
```suggestion
the [=verification material=] used to secure [=verifiable presentations=]. This 
```

2024-01-18 21:07 UTC, TallTed commented on index.html
> +Acceptably recent metadata regarding the verification material associated
```suggestion
Acceptably recent metadata regarding the [=verification material=] associated 
```

2024-01-24 17:58 UTC, dlongley approved these changes

2024-01-24 17:59 UTC, dlongley commented on terms.html
> +    Cryptographic information could be a public key or any other cryptographic data
Hmm, perhaps a slight tweak here to be more flexible:

```suggestion
    Information that could be a cryptographic public key or any other data 
```

2024-02-04 21:48 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-02-04 21:48 UTC, merged