Updating the text on vocabulary hashes
w3c/vc-data-model pull request #1454
Opened 2024-03-07 07:54 UTC by iherman

This is to handle #1442. It makes it clearer that all references are on JSON-LD.

Two notes for the future:

- If this PR is accepted and merged, a similar change should be done for the [DI spec's corresponding tables](https://www.w3.org/TR/vc-data-integrity/#contexts-and-vocabularies) for consistency (including the typesetting style for the hash values).
- _When going to Proposed REC_, the URL for the JSON-LD versions _must_ be changed in the text to use the final URL on W3C Date Space.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/pull/1454.html" title="Last updated on Mar 13, 2024, 7:21 AM UTC (3912181)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-data-model/1454/64cf5b1...3912181.html" title="Last updated on Mar 13, 2024, 7:21 AM UTC (3912181)">Diff</a>

2024-03-07 15:14 UTC, msporny commented on index.html
> +Cryptographic hashes are provided for all the JSON-LD contents to ensure that developers can
```suggestion
Cryptographic hashes are provided for all the JSON-LD content to ensure that developers can
```

2024-03-07 15:15 UTC, msporny approved these changes
Approved with minor grammatical fix.

2024-03-08 00:09 UTC, dlongley approved these changes

2024-03-08 00:10 UTC, decentralgabe approved these changes

2024-03-08 18:46 UTC, brentzundel approved these changes

2024-03-08 20:47 UTC, TallTed requested changes
To match later headings and discussion

2024-03-08 20:47 UTC, TallTed commented on index.html
>  verify that the contents of each file are correct.
```suggestion
verify that the content of each file is correct.
```

2024-03-11 17:38 UTC, TallTed requested changes

2024-03-11 17:38 UTC, TallTed commented on index.html
>  following command from a modern Unix command interface line:
```suggestion
It is possible to confirm the cryptographic digests listed above by running 
a command like the following (replacing `<DOCUMENT_URL>` and `<DIGEST_ALGORITHM>`
with appropriate values) through a modern UNIX-like OS command line interface:
```

2024-03-12 21:42 UTC, TallTed commented on index.html
> +a command like the following (replacing `<DOCUMENT_URL>` and `<DIGEST_ALGORITHM>`
whoops
```suggestion
a command like the following (replacing `&lt;DOCUMENT_URL>` and `&lt;DIGEST_ALGORITHM>`
```

2024-03-12 21:43 UTC, TallTed commented on index.html
>  `curl -sL -H "Accept: application/ld+json" &lt;DOCUMENT_URL> | openssl dgst -&ltDIGEST_ALGORITHM> -binary | openssl base64 -nopad -a`
```suggestion
`curl -sL -H "Accept: application/ld+json" &lt;DOCUMENT_URL> | openssl dgst -&lt;DIGEST_ALGORITHM> -binary | openssl base64 -nopad -a`
```

2024-03-13 07:20 UTC, iherman commented on index.html
> +a command like the following (replacing `<DOCUMENT_URL>` and `<DIGEST_ALGORITHM>`
Oops indeed :-)

2024-03-13 15:48 UTC, TallTed approved these changes

2024-03-13 16:13 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-13-vcwg#section4-5) on 2024-03-13

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.5. What does the hash values in §B.2 mean? (issue vc-data-model#1442)

_See github issue [vc-data-model#1442](https://github.com/w3c/vc-data-model/issues/1442)._




_See github pull request [vc-data-model#1454](https://github.com/w3c/vc-data-model/pull/1454)._




**Brent Zundel:** there is a PR, positive review, changes from TallTed. Please review. Should be merged soon.  

</details>

2024-03-13 16:55 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-03-13 16:56 UTC, merged