Support two different digest formats for resource integrity.
w3c/vc-data-model pull request #1492
Opened 2024-06-01 19:18 UTC by msporny

This PR is an attempt to address issue #1489 by allowing either `digestSRI` and/or `digestMultibase` to be used.

At this point, some WG Members have raised objections for [Option A](https://github.com/w3c/vc-data-model/issues/1489#issuecomment-2134164168) and [Option B](https://github.com/w3c/vc-data-model/issues/1489#issuecomment-2134164168). 

This PR implements [Option C](https://github.com/w3c/vc-data-model/issues/1489#issuecomment-2134164168).

If some subset of the WG objects to Option C, then we will need to determine which option will draw the least number of Formal Objections, pick one, and move on. Another option is to remove the feature from the specification entirely.

2024-06-01 20:02 UTC, longpd approved these changes
While I prefer Option B, Option C essentially asks the marketplace to pick approach most suitable for their use cases. Given where we are this sounds reasonable.

2024-06-02 00:00 UTC, dlongley approved these changes

2024-06-02 10:30 UTC, iherman approved these changes
I presume the exact placement for the formal specification of the property should be the subject of a separate PR ***if*** this options is accepted by the WG.

2024-06-03 20:36 UTC, brentzundel approved these changes

2024-06-04 20:00 UTC, TallTed requested changes

2024-06-04 20:00 UTC, TallTed commented on index.html
> +`digestSRI`, `digestMultibase`, and, optionally, the `mediaType` property.
There may be a better rephrasing. As I understand it, `mediaType` may accompany either `digestSRI` or `digestMultibase`, whichever is present, and only one of the latter two is allowed.
```suggestion
`digestSRI` or `digestMultibase` property, either of which MAY be 
accompanied by the additionally optional `mediaType` property.
```

2024-06-05 16:12 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-05-vcwg#section5-2) on 2024-06-05

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. Use digestMultibase with base64-url-nopad encoding for integrity. (pr vc-data-model#1490)

_See github pull request [vc-data-model#1490](https://github.com/w3c/vc-data-model/pull/1490)._




**Manu Sporny:** other thing we need to decide on is what digest formats we will support for related resource formats.  
… only support digestSri has objections that would turn into formal objections, same with only supporting digestMultibase.  

_See github pull request [vc-data-model#1492](https://github.com/w3c/vc-data-model/pull/1492)._




**Manu Sporny:** have not heard if anyone would formally object to supporting both, is in PR 1492.  
… at this point, need to ask group if anyone would object to supporting both digestSRI _and_ digestMultibase.  

**Brent Zundel:** the two options that are before the group that have a chance of avoiding formal objection are.  
… a, get rid of description of related resource.  
… b, support both, allow implementations to choose on digestSRI vs digestMultibase.  
… people don't like option b, but does anyone dislike it enough to formally object?  

> *Phillip Long:* +1 to let the market decide.

**Brent Zundel:** not hearing or seeing anyone object to the option to include both.  
… that is what we have decided to do.  

**Manu Sporny:** thank you, we will merge 1492, supporting both formats, to give more data to the group. I had to implement this this past weekend and it took 30min.  
… had to update respec-vc to generate hashes in both formats, took 30 mins, was not difficult.  

**Ted Thibodeau Jr.:** which digest form were you adding?  

**Manu Sporny:** both, added support for every variation of both digest formats.  

**Brent Zundel:** additional PRs we should look at?  

**Manu Sporny:** yes, next set, 6 of these to remove at risk issue markers (confidenceMethod, renderMethod, refreshService, terms of use).  

</details>

2024-06-09 12:46 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2024-06-09 12:46 UTC, merged