Add privacy considerations related to legal processes and coercion
w3c/vc-data-model pull request #1504
Opened 2024-06-19 20:38 UTC by msporny

This PR is an attempt to address issue #1502 by adding a few more privacy considerations related to legal processes and coercion.

/cc @zoracon

2024-06-20 03:02 UTC, decentralgabe approved these changes

2024-06-20 05:58 UTC, iherman approved these changes

2024-06-20 14:33 UTC, dlongley approved these changes

2024-06-20 17:17 UTC, longpd reviewed
The phrasing "such that a [=holder=] **can push back on** the over-collection of information that is unnecessary for the transaction." I presume means the holder can decline to share specific information requested.  Is that what this implies? If so, then saying that explicitly would be better.

2024-06-20 17:26 UTC, msporny commented
> I presume means the holder can decline to share specific information requested. Is that what this implies? If so, then saying that explicitly would be better.

Yes, that's what was meant, your text is more clear. I'll update the PR to use your text, thanks @longpd !

2024-06-21 22:12 UTC, brentzundel approved these changes

2024-06-22 02:22 UTC, zoracon approved these changes
The phrasing and changes overall address my initial concerns about addressing law enforcement, coercion, and the unreliability of private browsing.

2024-06-23 21:08 UTC, David-Chadwick approved these changes

2024-06-25 17:46 UTC, TallTed requested changes

2024-06-25 17:46 UTC, TallTed commented on index.html
>  push back on the over-collection of information that is unnecessary for the
@longpd's suggested revision —
```suggestion
information is being requested by a [=verifier=], such that a [=holder=] can
decline to share specific requested information that is unnecessary for the
```

2024-06-25 17:46 UTC, TallTed commented on index.html
> +third party.
```suggestion
It is possible, through legal processes, for [=issuers=], [=holders=], and/or
[=verifiers=] to be compelled to disclose private information to authorities,
such as law enforcement. It is also possible for the same private
information to be accidentally disclosed to an unauthorized party through a
software bug or security failure. Authors of legal processes and compliance
regimes are advised to draft guidelines that notify the [=subjects=] involved
when their private information is purposefully or accidentally disclosed to a
third party. Providers of software services are advised to be transparent about
known circumstances that might cause such private information to be shared with
a third party, and about the identity of any such third party.
```

2024-06-26 23:16 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-06-26 23:16 UTC, merged