Note that integrity protecting JSON-LD Contexts are allowed.
w3c/vc-data-model pull request #1537
Opened 2024-08-03 20:06 UTC by msporny

This PR is a partial fix for an issue raised in https://github.com/w3c/vc-data-integrity/issues/272 by noting that specification authors may require that JSON-LD Contexts are integrity protected by using the `relatedResource` feature.

2024-08-03 20:20 UTC, dlongley approved these changes

2024-08-04 06:55 UTC, iherman approved these changes
(This is just an editorial thing, take it or leave it.)

The term "specification authors" stopped me for a moment. I looked at the text overall, and this term is usually used making it clear what these people really define (new securing mechanism, etc). But the general term is not defined.

I presume that we are talking here about people authoring a new context file related to their applications. Maybe it is better to say "Specification authors who...", or simply replace the term by "Authors of new context files...".

2024-08-05 14:49 UTC, TallTed requested changes

2024-08-05 14:49 UTC, TallTed commented on index.html
> +[[[#integrity-of-related-resources]]], or an equivalent mechanism.
Acting on @iherman's comment
```suggestion
Authors of JSON-LD Contexts MAY require that those context files be integrity 
protected by using the `relatedResource` feature described in Section
[[[#integrity-of-related-resources]]] or an equivalent mechanism.
```

2024-08-05 14:56 UTC, dlongley commented on index.html
> +[[[#integrity-of-related-resources]]], or an equivalent mechanism.
I think what this is about is ecosystems that want to provide their own special profiling rules:

```suggestion
Profiles of this specification MAY require that JSON-LD Contexts are integrity
protected by using the `relatedResource` feature described in Section
[[[#integrity-of-related-resources]]], or an equivalent mechanism.
```

2024-08-05 14:56 UTC, dlongley commented on index.html
> +[[[#integrity-of-related-resources]]], or an equivalent mechanism.
Alternatively, for language that is more verbose but more similar to what is in the controller document:

```suggestion
Other specifications that profile this specification MAY require that JSON-LD
Contexts are integrity protected by using the `relatedResource` feature
described in Section [[[#integrity-of-related-resources]]], or an equivalent
mechanism.
```

2024-08-05 14:58 UTC, dlongley reviewed
Adding back my suggestions from my other review that happened at the same time as accepting another suggestion.

2024-08-05 14:58 UTC, dlongley commented on index.html
> +[[[#integrity-of-related-resources]]] or an equivalent mechanism.
```suggestion
Profiles of this specification MAY require that JSON-LD Contexts are integrity
protected by using the `relatedResource` feature described in Section
[[[#integrity-of-related-resources]]], or an equivalent mechanism.
```

2024-08-05 14:58 UTC, dlongley commented on index.html
> +[[[#integrity-of-related-resources]]] or an equivalent mechanism.
```suggestion
Other specifications that profile this specification MAY require that JSON-LD
Contexts are integrity protected by using the `relatedResource` feature
described in Section [[[#integrity-of-related-resources]]], or an equivalent
mechanism.
```

2024-08-05 15:13 UTC, TallTed requested changes

2024-08-05 15:13 UTC, TallTed commented on index.html
> +that JSON-LD Contexts are integrity protected by using the `relatedResource`
```suggestion
that JSON-LD Contexts be integrity protected by using the `relatedResource`
```

2024-08-05 15:33 UTC, dlongley commented on index.html
> +feature described in Section [[[#integrity-of-related-resources]]].
I think what this is about is ecosystems that want to provide their own special profiling rules (but also look below at the other option):

```suggestion
the [[[VC-DATA-INTEGRITY]]] specification. Profiles MAY require
that JSON-LD contexts be integrity protected by using the `relatedResource`
feature described in Section [[[#integrity-of-related-resources]]].
```

2024-08-05 15:33 UTC, dlongley commented on index.html
> +feature described in Section [[[#integrity-of-related-resources]]].
Alternatively, for language that is more verbose but more similar to what is in the controller document:

```suggestion
the [[[VC-DATA-INTEGRITY]]] specification. Other specifications that profile
this specification MAY require that JSON-LD contexts be integrity protected
by using the `relatedResource` feature described in Section
[[[#integrity-of-related-resources]]].
```

2024-08-05 16:04 UTC, decentralgabe approved these changes

2024-08-09 22:03 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-08-09 22:03 UTC, merged