Tweak media type conformance line.
w3c/vc-data-model pull request #1545
Opened 2024-08-14 20:09 UTC by BigBlueHat

A media type does not itself serialize, but rather identifies or
signals a serialization.

2024-08-14 20:12 UTC, TallTed approved these changes
lgtm

2024-08-14 20:13 UTC, dlongley approved these changes

2024-08-14 20:32 UTC, decentralgabe approved these changes

2024-08-15 06:54 UTC, iherman approved these changes

2024-08-15 15:10 UTC, selfissued commented on index.html
> +`application/vp`. A conforming document MUST be
```suggestion
A conforming document MUST be either a [=verifiable credential=]
when the `application/vc` media type is used or a
[=verifiable presentation=] when the
`application/vp` media type is used. A conforming document MUST be
```

2024-08-15 15:11 UTC, selfissued requested changes
The media types don't identify a serialization of the object.  They identify the type of the object.

2024-08-15 16:01 UTC, iherman commented
> The media types don't identify a serialization of the object. They identify the type of the object.

Generally true. But the vc (resp. vp) media type specification also specifies that it is a conforming JSON-LD document, so the original statement seems to be also true...

2024-08-15 16:05 UTC, TallTed commented on index.html
> +`application/vp`. A conforming document MUST be
```suggestion
A conforming document MUST be either a [=verifiable credential=]
with a media type of `application/vc` or a [=verifiable presentation=]
with a media type of `application/vp`. A conforming document MUST be
```

2024-08-17 16:02 UTC, msporny approved these changes

2024-08-19 17:51 UTC, selfissued approved these changes

2024-08-21 13:49 UTC, msporny commented
Editorial, multiple reviews, no changes requested, no remaining objections, merging.

2024-08-21 15:04 UTC, merged