Change usage patterns to patterns of use throughout
w3c/vc-data-model pull request #1561
Opened 2024-09-13 14:02 UTC by wip-abramson

This P.R. addresses issue #1555 

Just checking, I should only be changing the base index.html right? 

Also, as I was going through this I noticed the spec still has 32 uses of the word usage. I believe in the examples.

For example: "Usage of the credentialSubject property"

Should we also be changing these to Use?

2024-09-13 17:13 UTC, decentralgabe approved these changes

2024-09-13 17:36 UTC, TallTed commented
> Should we also be changing these to Use?

Yes, "use" is fully preferred to "usage". Depending on the specific phrasing, sometimes this change requires other minor rewording.

2024-09-15 22:04 UTC, msporny approved these changes

2024-09-16 20:57 UTC, TallTed commented
I've just reviewed every occurrence of `usage`. I think all can and should be replaced by `use`, though a few instances will require rephrasing of the neighboring or containing phrase. I can produce a PR for this, after this one (#1561) is merged; or you could change them on your branch, within this PR, and I can then suggest the rephrasing (which I cannot suggest until the changes of `usage` makes the neighboring lines available for change requests).

2024-09-18 10:22 UTC, wip-abramson commented
@TallTed I have replaced usage with use throughout the spec. I have mostly left any additional rephrasing required to you as suggested.

I renamed the P.R. to more accurately reflect the changes

2024-09-18 17:21 UTC, TallTed requested changes
Editorial. Small grammar fixes.

2024-09-18 17:21 UTC, TallTed commented on index.html
> +          title="Use of the name and description property">
```suggestion
          title="Use of the name and description properties">
```

2024-09-18 17:21 UTC, TallTed commented on index.html
> +        <pre class="example nohighlight vc" title="Use of issuer property"
```suggestion
        <pre class="example nohighlight vc" title="Use of the issuer property"
```

2024-09-18 17:21 UTC, TallTed commented on index.html
> +          title="Use of issuer expanded property"
```suggestion
          title="Expanded use of the issuer property"
```

2024-09-20 13:23 UTC, wip-abramson commented on index.html
>  [=verifiable credentials=].
```suggestion
Privacy violations related to the use of [=verifiable credentials=] occur when
unintended or unexpected correlation arises from the presentation of those
[=verifiable credentials=].
```

Is this better?

2024-09-20 18:10 UTC, TallTed commented on index.html
>  [=verifiable credentials=].
I've updated my suggestion to match @wip-abramson's.

2024-09-27 15:29 UTC, TallTed reviewed
"utiliz{ed,ation,ing}" should also all become "us{ed,e,ing}", like these two.

2024-09-27 15:29 UTC, TallTed commented on index.html
>  form</a> MUST be utilized for all representations of the data model using the
```suggestion
form</a> MUST be used for all representations of the data model using the
```

2024-09-27 15:29 UTC, TallTed commented on index.html
>  information in this data model is expected to be utilized by [=verifiers=]
```suggestion
information in this data model is expected to be used by [=verifiers=]
```

2024-09-27 15:57 UTC, wip-abramson commented
@TallTed I believe this addresses all uses of utiliz{e,es,ing,ed} throughout the spec.

2024-09-27 15:57 UTC, TallTed approved these changes

2024-09-30 18:27 UTC, msporny commented
There are merge conflicts with the huge security considerations grammar fix PR. Please fix the merge conflicts @wip-abramson and we can get this merged.

2024-10-03 16:04 UTC, wip-abramson commented
@msporny should be good to go

2024-10-03 18:34 UTC, TallTed requested changes
Small, editorial

2024-10-03 18:34 UTC, TallTed commented on index.html
> +presented (all liquor stores, bars, adult stores, lottery sellers, and so on).
```suggestion
The centralized server can correlate uses of the [=credential=] across
interactions. For example, if a [=credential=] is used to prove age in this
manner, the centralized service could know everywhere that [=credential=] was
presented (all liquor stores, bars, adult stores, lottery sellers, and so on).
```

2024-10-03 18:34 UTC, TallTed commented on index.html
> +optional mechanism for ensuring content integrity of external
```suggestion
optional mechanism for ensuring the integrity of the content of external
```

2024-10-03 18:46 UTC, msporny commented
@wip-abramson can you take care of @TallTed's suggestions so we can get this merged? https://github.com/w3c/vc-data-model/pull/1561#pullrequestreview-2346395835

I would, but it's not showing up in my source view for some reason... wonder if Ted submitted his changes based on some different/disconnected commit hash?

2024-10-03 19:39 UTC, TallTed commented
Very odd. I made my suggestions on the `/files` view, but now that doesn't obviously include these paragraphs, and digging deeper, they're in the "untouchable" blue section of the document. Redone in #1569.

2024-10-03 19:39 UTC, TallTed commented on index.html
> +optional mechanism for ensuring content integrity of external
Redone in #1569

2024-10-03 19:39 UTC, TallTed commented on index.html
> +presented (all liquor stores, bars, adult stores, lottery sellers, and so on).
Redone in #1569

2024-10-05 17:40 UTC, merged

2024-10-05 17:41 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.