Update "refreshService" example to VCDM2.0
w3c/vc-data-model pull request #1566
Opened 2024-09-24 15:05 UTC by peacekeeper

2024-09-30 18:31 UTC, msporny requested changes
While it is true that the example is a v1 example, the group also decided to use real world / representative examples. The credential refresh example (which is what the TruAge example uses) only uses v1, not v2 and upgrading it to v2 would result in an example that isn't grounded in the real world. 

I suggest we keep this as-is for now until we can get confirmation from the US convenience retail industry on their plans to upgrade to v2.0 for their credential refresh mechanism. AFAIK, they have no plans to start the upgrade process (which will take 2-3 years once started) until v2.0 is out.

2024-10-14 08:24 UTC, iherman commented
> 
> I suggest we keep this as-is for now until we can get confirmation from the US convenience retail industry on their plans to upgrade to v2.0 for their credential refresh mechanism. AFAIK, they have no plans to start the upgrade process (which will take 2-3 years once started) until v2.0 is out.

I do not think I agree. The example in the document must be along the line of this specification, and having a v1 example can become extremely confusing. It may not be a good idea for a new CR2 version, which is meant to be the Proposed Rec...

One possibility is to add a note making what you describe explicit, ie, that the example does not represent current deployment 100% because the US convenience retail industry has not yet upgraded to V2. (I guess that would require to use an imaginary `https://w3id.org/age/v2` as a context file as well.)

A suboptimal solution is to leave things as is but add a note which makes it explicitly that the example is incorrect V2 and should be updated to V2 when the time comes. But that still is confusing if people try to learn from examples and do not really read the spec... Hence suboptimal.

2024-10-14 11:29 UTC, chaals commented
I agree with Ivan's thinking here. People do copy examples and work from them, instead of carefully reading the spec, and it is important that the spec itself at least encourages that to work out right.

Explaining why an example isn't practising what the spec preaches helps, but is suboptimal, and leaving an example that doesn't match without very clear explanation of that is IMHO a Bad Idea™.

One approach might be to show the example from reality, noting the situation, and accompany it with an example of how it would look when updated.

(I do think it's good to have examples from reality, even though they represent a snapshot from the past by the time you publish them. But making that a strict test for anything labeled example is IMHO not the most helpful way to apply the principle.)

2024-10-14 20:43 UTC, msporny commented
Another option that ***we should definitely not do right now*** is to define refresh services in the WG... but that can wait for v2.1. :)

@peacekeeper, would you mind modifying this PR to add a warning about the example as @iherman and @chaals have suggested (even though it's suboptimal)?

2024-10-20 13:21 UTC, Lp2125 commented
![IMG-20241019-WA0024](https://github.com/user-attachments/assets/b1e75d0e-6127-4ffe-a4ac-2200caca5079)

2024-11-21 23:30 UTC, brentzundel commented
I would rather not have an example than have an example that doesn't conform to the specification, regardless of how realistic the example is.
I would rather have a completely invented example that conforms to the specification than a real-world example that doesn't.

Keeping the refreshService example as is would be a disservice to implementers, even with a warning.

2024-11-22 02:32 UTC, selfissued commented
I agree with @brentzundel that either the example should match THIS spec or it should be deleted.

2024-11-22 05:24 UTC, iherman commented
>  I would rather have a completely invented example that conforms to the specification than a real-world example that doesn't.

Yes.

2025-01-12 23:58 UTC, msporny commented
@peacekeeper can you make modifications to this PR given all the WG input above? It looks like the options are:

* Remove all examples of `refreshService`.
* Add a fake (but conforming) example  of `refreshService` (like an ExampleRefreshService).

I'd be ok with the second option, and it seems like others would as well. Any chance you can modify this PR? We need to find a way to merging this PR or closing it and trying again.

2025-01-15 17:05 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2025-01-15-vcwg#section1-4) on 2025-01-15

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.4. Update "refreshService" example to VCDM2.0 (pr vc-data-model#1566)

_See github pull request [vc-data-model#1566](https://github.com/w3c/vc-data-model/pull/1566)._




**Brent Zundel:** This PR update refreshService.  

**Manu Sporny:** this was initially to address using real examples in the specification.  
… This was done mostly accept for refreshService.  
… We dont have a v2.0 example.  
… I think there is pushback to using an 2.0 example.  

</details>

2025-01-18 18:40 UTC, msporny approved these changes
Based on the discussion this past week, I'm withdrawing my objection to updating the example. 

I have ensured that the new example is a valid JSON-LD example (it is).

2025-01-18 18:41 UTC, msporny commented
Editorial, multiple reviews, changes requested (but not made), no objections, merging.

2025-01-18 18:41 UTC, merged